import { ArchwayCoin, ArchwayCoinReversed } from "./BrandMark";

const paper = "#faf6f1";
const ink = "#292522";
const umber = "#655d56";
const signal = "#ff3c00";
const hairline = "#ded7d0";
const muted = "#837a72";

const style = `
  .brand-plate{min-height:1000px;width:950px;box-sizing:border-box;background:${paper};color:${ink};padding:34px 56px 42px;font-family:"Schibsted Grotesk",sans-serif}
  .brand-head{height:35px;border-bottom:1px solid ${hairline};display:flex;justify-content:space-between;align-items:flex-start;color:${muted};font:10px/1.2 "DM Mono",monospace;letter-spacing:.14em;text-transform:uppercase}
  .brand-title{font:500 22px/1 "Fraunces",serif;letter-spacing:-.02em;margin:26px 0 8px}.brand-kicker{font:10px/1.2 "DM Mono",monospace;letter-spacing:.12em;color:${muted};text-transform:uppercase}
  .merch-section{border-top:1px solid ${hairline};margin-top:22px;padding-top:13px}.merch-label{display:flex;justify-content:space-between;color:${muted};font:9px "DM Mono",monospace;letter-spacing:.12em;text-transform:uppercase;margin-bottom:13px}
  .merch-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.merch-card{border:1px solid ${hairline};min-height:220px;padding:16px;position:relative;overflow:hidden}.merch-card h2{font:16px "Fraunces",serif;margin:0 0 5px}.merch-note{color:${muted};font:9px "DM Mono",monospace;letter-spacing:.08em;text-transform:uppercase}.tote{height:156px;width:156px;margin:12px auto 0;background:${ink};border-radius:4px 4px 18px 18px;position:relative;display:grid;place-items:center}.tote:before,.tote:after{content:"";position:absolute;top:-28px;width:39px;height:53px;border:5px solid ${ink};border-bottom:0;border-radius:25px 25px 0 0}.tote:before{left:28px}.tote:after{right:28px}.tote-coin{border:1px solid ${umber};padding:8px;border-radius:50%}.pin-stage{height:156px;display:grid;place-items:center;background:#f3ede7;margin-top:12px}.pin{width:80px;height:80px;border-radius:50%;background:${ink};border:5px solid ${umber};display:grid;place-items:center;box-shadow:0 3px 0 ${umber}}.badge-stage{display:flex;align-items:center;gap:25px;height:156px;margin-top:12px;padding:17px;background:${ink};color:${paper}}.lanyard{width:42px;height:156px;background:${umber};position:relative;transform:rotate(7deg)}.lanyard:before{content:"";position:absolute;left:12px;width:18px;height:156px;background:${ink}}.badge{background:${paper};color:${ink};width:160px;height:112px;padding:13px;box-shadow:5px 5px 0 ${umber}}.badge-name{font:21px "Fraunces",serif;margin:16px 0 5px}.badge-meta{font:8px "DM Mono",monospace;letter-spacing:.12em;color:${muted}}.sign-stage{height:110px;background:${ink};margin-top:12px;display:flex;align-items:center;gap:22px;padding:0 28px;color:${paper}}.sign-word{font:25px "Fraunces",serif;letter-spacing:-.04em}.sign-meta{font:8px "DM Mono",monospace;color:#9b9289;letter-spacing:.11em;border-left:1px solid ${umber};padding-left:18px}
`;

export default function BrandMerch() {
  return <main className="brand-plate"><style>{style}</style><header className="brand-head"><span>ARCANUM BRAND — MERCH / ENVIRONMENT</span><span>OBJECTS · 03</span></header>
    <h1 className="brand-title">Quiet signals in the room.</h1><div className="brand-kicker">FLAT-PREMIUM MOCKUPS / WEAR · CARRY · GATHER · SIGN</div>
    <section className="merch-section"><div className="merch-label"><span>CARRY / EMBOSSED TOTE</span><span>INK CANVAS · PAPER RELIEF</span></div><div className="merch-grid"><article className="merch-card"><h2>The everyday vault.</h2><div className="merch-note">coin mark · 1:1 application · blind emboss suggestion</div><div className="tote"><div className="tote-coin"><ArchwayCoinReversed size={86}/></div></div></article><article className="merch-card"><h2>Enamel pin / 24px mark.</h2><div className="merch-note">umber rim · no tonal trickery · signal point</div><div className="pin-stage"><div className="pin"><ArchwayCoinReversed size={59}/></div></div></article></div></section>
    <section className="merch-section"><div className="merch-label"><span>GATHER / EVENT BADGE</span><span>LANYARD · NAME PLATE</span></div><div className="merch-grid"><article className="merch-card"><h2>One pass, one policy.</h2><div className="merch-note">soft umber webbing · paper card · square hierarchy</div><div className="badge-stage"><div className="lanyard" /><div className="badge"><ArchwayCoin size={24}/><div className="badge-name">Mira Sen</div><div className="badge-meta">ARCANUM / POLICY</div></div></div></article><article className="merch-card"><h2>The office mark.</h2><div className="merch-note">reversed coin · architectural quiet</div><div className="sign-stage"><ArchwayCoinReversed size={59}/><div className="sign-word">ARCANUM</div><div className="sign-meta">GOVERNED<br/>TREASURY</div></div></article></div></section>
    <p style={{ marginTop: 28, color: "#9b9289", font: "9px 'DM Mono',monospace", letterSpacing: ".1em", textTransform: "uppercase" }}>ONE MARK / MANY SURFACES — THE ARCHWAY REMAINS THE CONSTANT.</p>
  </main>;
}