const paper="#faf6f1",ink="#292522",umber="#655d56",signal="#ff3c00",hairline="#ded7d0",guide="#9b9289";
/*
 * BEACON GRID / 32px module. Source dot center (200,326), broadcast axis x=200.
 * Three open arcs have radii 72/108/144 and equal 56° sweeps, centered at
 * 270° (upward). G2 side control points are symmetric and the 16px gap between
 * arcs is 1/2 the 32px module, keeping broadcast bands separate at 16px.
 */
const arcs=[{r:72,w:2},{r:108,w:1.7},{r:144,w:1.35}];
const arc=(r:number)=>`M ${200-r*.829} ${326-r*.559} A ${r} ${r} 0 0 1 ${200+r*.829} ${326-r*.559}`;
const source="M 200 312 A 14 14 0 1 1 200 340 A 14 14 0 1 1 200 312 Z";
const style=`.precision-plate{min-height:100vh;width:100%;box-sizing:border-box;padding:30px 34px 26px;background:${paper};color:${ink};display:flex;flex-direction:column;font-family:"IBM Plex Mono","Courier New",monospace}.precision-meta{display:flex;justify-content:space-between;gap:24px;color:#837a72;font-size:10px;line-height:1.2;letter-spacing:.14em;text-transform:uppercase;white-space:nowrap}.precision-meta span:last-child{text-align:right}.precision-hero{flex:1 1 auto;min-height:414px;display:grid;place-items:center}.hero-svg{width:min(380px,76vw);height:auto;display:block}.construction{border-top:1px solid ${hairline};min-height:174px;display:grid;place-items:center}.construction-svg{width:min(480px,92vw);height:168px;display:block}.scale-row{display:flex;justify-content:center;align-items:end;gap:24px;padding-top:8px;color:#9b9289;font-size:8px;letter-spacing:.08em;text-transform:uppercase}.scale-cell{display:flex;flex-direction:column;align-items:center;gap:5px}.scale-cell svg{display:block}.rationale{margin:15px 0 0;color:#9b9289;font-size:9px;line-height:1.4;letter-spacing:.1em;text-transform:uppercase}@media(max-width:520px){.precision-plate{padding:25px 22px 20px}.precision-hero{min-height:368px}.construction{min-height:158px}.construction-svg{height:150px}.scale-row{gap:18px}}`;
function Construction(){return <svg viewBox="0 0 400 240" className="construction-svg" role="img" aria-label="Beacon construction"><g fill="none" stroke={guide} strokeWidth="1" opacity=".72"><path d="M 200 20 V 224 M 76 206 H 324"/><circle cx="200" cy="206" r="72"/><circle cx="200" cy="206" r="108"/><circle cx="200" cy="206" r="144"/></g><g fill={guide} fontFamily='"IBM Plex Mono",monospace' fontSize="8"><text x="306" y="32">56° SWEEP</text><text x="306" y="122">32PX RADIAL</text></g>{arcs.map((a)=><path key={a.r} d={arc(a.r)} fill="none" stroke={a.r===72?ink:umber} strokeWidth={a.w} opacity=".3"/>)}<path d={source} fill={signal} opacity=".7" transform="translate(0 -120)"/></svg>}
export default function TheBeacon(){return <main className="precision-plate"><style>{style}</style><header className="precision-meta"><span>ARCANUM — STUDY 55/55</span><span>THE BEACON</span></header><section className="precision-hero"><svg viewBox="0 0 400 400" className="hero-svg" role="img" aria-label="Beacon broadcast arcs"><g>{arcs.map(a=><path key={a.r} d={arc(a.r)} fill="none" stroke={a.r===72?ink:umber} strokeWidth={a.w}/>)}</g><path d={source} fill={signal}/></svg></section><section className="construction"><Construction/></section><div className="scale-row">{[64,32,16].map(size=><div className="scale-cell" key={size}><svg viewBox="0 0 400 400" style={{width:size,height:size}}>{arcs.map(a=><path key={a.r} d={arc(a.r)} fill="none" stroke={a.r===72?ink:umber} strokeWidth={a.w}/>)}<path d={source} fill={signal}/></svg><span>{size}px</span></div>)}</div><p className="rationale">THE HUMAN SOURCE BROADCASTS EVERY GOVERNED ACTION INTO THE OPEN.</p></main>}