const paper="#faf6f1",ink="#292522",umber="#655d56",signal="#ff3c00",hairline="#ded7d0",guide="#9b9289";
/*
 * IMPRINT GRID / 32px module. Four open Bézier whorls use radii 92,72,52,32.
 * Sweeps are 276°, with every opening aligned at the 12 o'clock channel.
 * G2 continuity is preserved by equal tangent directions at each endpoint;
 * the 12px channel is 3× the 4px fine stroke, so the path remains open at 16px.
 */
const arcs=[{r:92,w:2.2},{r:72,w:1.8},{r:52,w:1.45},{r:32,w:1.2}];
const arcPath=(r:number)=>`M 200 ${200-r} A ${r} ${r} 0 1 1 ${200+r*0.997} ${200-r*0.14}`;
const point="M 200 187 A 13 13 0 1 1 200 213 A 13 13 0 1 1 200 187 Z";
const style=`.precision-plate{min-height:100vh;width:100%;box-sizing:border-box;padding:30px 34px 26px;background:${paper};color:${ink};display:flex;flex-direction:column;font-family:"IBM Plex Mono","Courier New",monospace}.precision-meta{display:flex;justify-content:space-between;gap:24px;color:#837a72;font-size:10px;line-height:1.2;letter-spacing:.14em;text-transform:uppercase;white-space:nowrap}.precision-meta span:last-child{text-align:right}.precision-hero{flex:1 1 auto;min-height:414px;display:grid;place-items:center}.hero-svg{width:min(380px,76vw);height:auto;display:block}.construction{border-top:1px solid ${hairline};min-height:174px;display:grid;place-items:center}.construction-svg{width:min(480px,92vw);height:168px;display:block}.scale-row{display:flex;justify-content:center;align-items:end;gap:24px;padding-top:8px;color:#9b9289;font-size:8px;letter-spacing:.08em;text-transform:uppercase}.scale-cell{display:flex;flex-direction:column;align-items:center;gap:5px}.scale-cell svg{display:block}.rationale{margin:15px 0 0;color:#9b9289;font-size:9px;line-height:1.4;letter-spacing:.1em;text-transform:uppercase}@media(max-width:520px){.precision-plate{padding:25px 22px 20px}.precision-hero{min-height:368px}.construction{min-height:158px}.construction-svg{height:150px}.scale-row{gap:18px}}`;
function Construction(){return <svg viewBox="0 0 400 240" className="construction-svg" role="img" aria-label="Imprint arc construction"><g fill="none" stroke={guide} strokeWidth="1" opacity=".7"><circle cx="200" cy="120" r="92"/><circle cx="200" cy="120" r="72"/><circle cx="200" cy="120" r="52"/><circle cx="200" cy="120" r="32"/><path d="M 200 12 V 228 M 186 120 H 214" strokeDasharray="4 4"/></g><g fill={guide} fontFamily='"IBM Plex Mono",monospace' fontSize="8" letterSpacing=".08em"><text x="300" y="36">276° SWEEP</text><text x="300" y="122">12PX CHANNEL</text></g>{arcs.map((a,i)=><path key={a.r} d={arcPath(a.r).replaceAll("200 ","200 ")} fill="none" stroke={i<2?ink:umber} strokeWidth={a.w} opacity=".3"/>)}<path d={point} fill={signal} opacity=".7" transform="translate(0 -80)"/></svg>}
export default function TheImprint(){return <main className="precision-plate"><style>{style}</style><header className="precision-meta"><span>ARCANUM — STUDY 53/55</span><span>THE IMPRINT</span></header><section className="precision-hero"><svg viewBox="0 0 400 400" className="hero-svg" role="img" aria-label="Four open fingerprint arcs"><g fill="none">{arcs.map((a,i)=><path key={a.r} d={arcPath(a.r)} stroke={i<2?ink:umber} strokeWidth={a.w}/>)}</g><path d={point} fill={signal}/></svg></section><section className="construction"><Construction/></section><div className="scale-row">{[64,32,16].map(size=><div className="scale-cell" key={size}><svg viewBox="0 0 400 400" style={{width:size,height:size}}>{arcs.map((a,i)=><path key={a.r} d={arcPath(a.r)} fill="none" stroke={i<2?ink:umber} strokeWidth={a.w}/>)}<path d={point} fill={signal}/></svg><span>{size}px</span></div>)}</div><p className="rationale">FOUR OPEN PATHS LEAVE ONE AUDITABLE CHANNEL TO THE HUMAN IMPRINT.</p></main>}