const paper = "#faf6f1";
const ink = "#292522";
const signal = "#ff3c00";
const hairline = "#ded7d0";
const guide = "#9b9289";

/*
 * SENTINEL CONSTRUCTION / 32px base module
 * Symmetry axis x=180. Guard bounds x=54..306, y=62..348.
 * Each guard is one architectural filled path. Its inner edge is the
 * right/left half of a complete shield contour: a narrow crown slit,
 * straight-tensioned shoulders, and an 8px bottom sliver at the point.
 * The second guard is generated by exact reflection, never redrawn by eye.
 */
const leftGuard =
  "M 54 76 L 108 62 L 146 74 L 176 86 " +
  "L 140 110 " +
  "C 132 146 124 184 124 220 " +
  "C 124 258 142 291 176 322 " +
  "L 176 334 L 148 348 " +
  "L 108 334 L 78 302 L 60 260 L 54 200 L 56 130 Z";

// The human watch sits in the carved void, not outside the guards.
const watchPoint =
  "M 180 153 C 188.3 153 195 159.7 195 168 C 195 176.3 188.3 183 180 183 C 171.7 183 165 176.3 165 168 C 165 159.7 171.7 153 180 153 Z";

function ConstructionSystem() {
  return (
    <svg viewBox="0 0 360 400" role="img" aria-label="The Sentinel construction system" className="construction-svg">
      <g fill="none" stroke={guide} strokeWidth="1" opacity="0.62">
        {/* The center axis, mirrored guard bounds, and real inner-edge shield void are documented here. */}
        <path d="M 180 48 V 348 M 68 72 H 292 M 66 224 H 294 M 122 328 H 238" />
        <path d="M 54 76 L 108 62 L 146 74 L 176 86 L 140 110 C 132 146 124 184 124 220 C 124 258 142 291 176 322" />
        <path d="M 306 76 L 252 62 L 214 74 L 184 86 L 220 110 C 228 146 236 184 236 220 C 236 258 218 291 184 322" />
        <path d="M 176 322 H 184" strokeDasharray="3 3" />
        <path d="M 180 50 V 350" strokeDasharray="3 4" />
      </g>
      <g stroke={guide} strokeWidth="1" opacity="0.72">
        {/* 32px marks show the exact mirrored spans and 30px watch-point datum. */}
        <path d="M 54 56 V 68 M 86 56 V 68 M 118 56 V 68 M 150 56 V 68 M 182 56 V 68 M 214 56 V 68 M 246 56 V 68 M 278 56 V 68 M 306 56 V 68" />
        <path d="M 48 62 H 60 M 48 94 H 60 M 48 126 H 60 M 48 158 H 60 M 48 190 H 60 M 48 222 H 60 M 48 254 H 60 M 48 286 H 60 M 48 318 H 60 M 48 348 H 60" />
      </g>
      <path d={leftGuard} fill={ink} opacity="0.3" />
      <path d={leftGuard} fill={ink} opacity="0.3" transform="translate(360 0) scale(-1 1)" />
      <path d={watchPoint} fill={signal} opacity="0.72" />
    </svg>
  );
}

export default function TheSentinel() {
  return (
    <main className="arcanum-plate sentinel-plate">
      <style>{`
        .arcanum-plate {
          min-height: 100vh;
          width: 100%;
          box-sizing: border-box;
          padding: 30px 34px 28px;
          background: ${paper};
          color: ${ink};
          display: flex;
          flex-direction: column;
          font-family: "IBM Plex Mono", "Courier New", monospace;
        }
        .plate-meta {
          display: flex;
          justify-content: space-between;
          gap: 24px;
          color: #837a72;
          font-size: 10px;
          line-height: 1.2;
          letter-spacing: .14em;
          text-transform: uppercase;
          white-space: nowrap;
        }
        .plate-meta span:last-child { text-align: right; }
        .plate-hero {
          flex: 1 1 auto;
          min-height: 422px;
          display: grid;
          place-items: center;
        }
        .hero-svg {
          width: min(380px, 74vw);
          height: auto;
          display: block;
        }
        .construction {
          border-top: 1px solid ${hairline};
          min-height: 216px;
          display: grid;
          place-items: center;
        }
        .construction-svg {
          width: min(180px, 44vw);
          height: auto;
          display: block;
        }
        .plate-rationale {
          margin: 19px 0 0;
          color: ${guide};
          font-size: 9px;
          line-height: 1.4;
          letter-spacing: .1em;
          text-transform: uppercase;
        }
        @media (max-width: 520px) {
          .arcanum-plate { padding: 25px 22px 22px; }
          .plate-hero { min-height: 372px; }
          .construction { min-height: 186px; }
          .plate-rationale { margin-top: 15px; }
        }
      `}</style>
      <header className="plate-meta">
        <span>ARCANUM — STUDY 38/38</span>
        <span>THE SENTINEL</span>
      </header>
      <section className="plate-hero" aria-label="Finished Sentinel symbol">
        <svg viewBox="0 0 360 400" role="img" aria-label="Mirrored guards creating a shield-shaped negative space" className="hero-svg">
          {/* Two solid mirrored guardians. Their inner edges are the complete shield contour:
              narrow crown, tensioned sides, and an 8px bottom sliver at the implied point. */}
          <path d={leftGuard} fill={ink} />
          <path d={leftGuard} fill={ink} transform="translate(360 0) scale(-1 1)" />
          {/* Optical correction: the 8px bottom sliver prevents the negative shield from dissolving into a vase. */}
          {/* The signal point is centered on x=180, y=168: the human is vigilance, not an ornament. */}
          <path d={watchPoint} fill={signal} />
        </svg>
      </section>
      <section className="construction" aria-label="Sentinel construction drawing">
        <ConstructionSystem />
      </section>
      <p className="plate-rationale">TWO GUARDS CARVE A SHIELD; ONE HUMAN WATCH KEEPS IT OPEN.</p>
    </main>
  );
}