import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const contracts = [
  "GuardedWallet",
  "PolicyEngine",
  "EscalationManager",
  "AnomalyOracle",
  "VendorRegistry",
  "WalletFactory",
];

const abis = contracts.map((name) => {
  const output = execFileSync("forge", ["inspect", name, "abi", "--json"], {
    cwd: root,
    encoding: "utf8",
  });
  return { name, abi: JSON.parse(output) };
});

mkdirSync(join(root, "abis"), { recursive: true });
for (const { name, abi } of abis) {
  writeFileSync(join(root, "abis", `${name}.json`), `${JSON.stringify(abi, null, 2)}\n`);
}

const banner =
  "// Generated by scripts/export-abis.mjs from forge inspect. Do not edit by hand.\n\n";
const body = abis
  .map(({ name, abi }) => `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`)
  .join("\n");
writeFileSync(join(root, "index.ts"), banner + body);
execFileSync("npx", ["biome", "format", "--write", "index.ts"], { cwd: root, stdio: "inherit" });
