import { useMemo, useState, type CSSProperties, type ReactNode } from "react";
import { Header } from "./_shared/Header";

const navItems = ["DASHBOARD", "AGENTS", "VENDORS", "LEDGER", "ESCALATIONS", "ANOMALIES"];
type AgentStatus = "ACTIVE" | "FROZEN" | "IDLE";
type Agent = { name: string; wallet: string; status: AgentStatus; posture: number; spend: string; cap: string; categories: string[]; event: string; eventTime: string; doctrine: string; decisions: string[] };

const agents: Agent[] = [
  { name: "procurement-bot", wallet: "0x3f…9a2c", status: "ACTIVE", posture: 94, spend: "$1,842.20", cap: "$5,000", categories: ["cloud", "infra"], event: "Reserved capacity · AWS", eventTime: "09:41 UTC", doctrine: "Source approved infrastructure and settle invoices within the procurement policy.", decisions: ["AWS · $184.20 · APPROVED", "AWS Bedrock · $316.40 · APPROVED", "OpenAI · $740.00 · REJECTED"] },
  { name: "support-agent", wallet: "0x71…4be1", status: "ACTIVE", posture: 81, spend: "$740.00", cap: "$2,000", categories: ["model", "support"], event: "Token replenishment · OpenAI", eventTime: "09:39 UTC", doctrine: "Keep customer support responsive while routing unusual model spend to a human.", decisions: ["OpenAI · $212.80 · REJECTED", "OpenAI · $96.20 · APPROVED", "AWS · $48.00 · APPROVED"] },
  { name: "growth-bot", wallet: "0xa8…c912", status: "FROZEN", posture: 58, spend: "$2,100.00", cap: "$3,000", categories: ["model", "campaign"], event: "Campaign inference · Anthropic", eventTime: "09:36 UTC", doctrine: "Run campaign analysis with a hard boundary around new counterparties.", decisions: ["Anthropic · $2,100.00 · ESCALATED", "Anthropic · $480.00 · APPROVED", "OpenAI · $740.00 · REJECTED"] },
  { name: "research-bot", wallet: "0x18…d0f6", status: "ACTIVE", posture: 88, spend: "$96.20", cap: "$1,500", categories: ["compute", "research"], event: "Vector index run · Qdrant", eventTime: "09:34 UTC", doctrine: "Explore approved research vendors; every reservation is reviewable.", decisions: ["Qdrant Cloud · $96.20 · APPROVED", "AWS Bedrock · $96.20 · ESCALATED", "AWS · $48.00 · APPROVED"] },
  { name: "ledger-scribe", wallet: "0x92…1b4e", status: "IDLE", posture: 72, spend: "$0.00", cap: "$500", categories: ["ledger"], event: "No event in 24h", eventTime: "yesterday", doctrine: "Maintain a clean record of policy decisions and settlement receipts.", decisions: ["AWS · $48.00 · APPROVED", "Qdrant Cloud · $14.80 · APPROVED"] },
];

function Arrow() { return <span aria-hidden="true" className="ml-1.5 inline-block transition-transform duration-[220ms] group-hover:translate-x-1">→</span>; }
function StatusPill({ status }: { status: AgentStatus }) {
  const styles = { ACTIVE: "bg-[#e7f0e5] text-[#3f653e]", FROZEN: "bg-[#292522] text-[#faf6f1]", IDLE: "border border-[#ded7d0] text-[#837a72]" };
  return <span className={`inline-flex rounded-full px-2.5 py-1 font-mono text-[9px] tracking-[.12em] ${styles[status]}`}>{status}</span>;
}
function Shell({ children }: { children: ReactNode }) {
  return <main className="min-h-[100dvh] bg-[#faf6f1] text-[#292522]" style={{ fontFamily: "'Inter Tight', sans-serif" }}><style>{`
    @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Inter+Tight:wght@400;500;600;700&display=swap');
    .font-mono{font-family:'DM Mono',monospace}.agents-reveal{animation:agentsIn 420ms cubic-bezier(.16,1,.3,1) calc(var(--i,0) * 90ms) both}@keyframes agentsIn{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}
    .warm-pill{position:relative;isolation:isolate;overflow:hidden;transition:transform 220ms cubic-bezier(.16,1,.3,1),box-shadow 320ms cubic-bezier(.16,1,.3,1),color 220ms ease,border-color 220ms ease;box-shadow:0 1px 2px rgba(41,37,34,.06)}.warm-pill::before{content:"";position:absolute;inset:0;z-index:-1;border-radius:inherit;background:#d63200;transform:translateY(102%);transition:transform 320ms cubic-bezier(.16,1,.3,1)}.warm-pill:hover{transform:translateY(-1px);box-shadow:0 10px 28px -8px rgba(255,60,0,.42)}.warm-pill:hover::before{transform:translateY(0)}.warm-pill-ghost::before{background:#292522}.warm-pill-ghost:hover{color:#faf6f1;border-color:#292522}
    .agent-row{transition:transform 220ms cubic-bezier(.16,1,.3,1),background-color 220ms ease}.agent-row:hover{transform:translateX(3px);background:#f5f0ea}.meter{height:4px;background:#e3dcd5}.meter>span{display:block;height:100%;background:#292522;transform-origin:left;transition:transform 420ms cubic-bezier(.16,1,.3,1)}
    @media (prefers-reduced-motion:reduce){.agents-reveal,.warm-pill,.warm-pill::before,.agent-row{animation:none;transition:none}}
  `}</style><Header active="AGENTS" />{children}</main>;
}

function Agents() {
  const [filter, setFilter] = useState<"ALL" | AgentStatus>("ALL");
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState(agents[0].name);
  const [frozen, setFrozen] = useState<string[]>([]);
  const [deployOpen, setDeployOpen] = useState(false);
  const [walletName, setWalletName] = useState("");
  const visibleAgents = useMemo(() => agents.filter((agent) => (filter === "ALL" || agent.status === filter) && agent.name.includes(query.toLowerCase())), [filter, query]);
  const selectedAgent = agents.find((agent) => agent.name === selected) ?? agents[0];
  const selectedStatus = frozen.includes(selectedAgent.name) ? "FROZEN" : selectedAgent.status;
  const toggleFreeze = () => setFrozen((current) => current.includes(selectedAgent.name) ? current.filter((name) => name !== selectedAgent.name) : [...current, selectedAgent.name]);
   return <Shell><div id="top" className="mx-auto max-w-[1400px] px-5 py-9 md:px-8 md:py-10"><div className="agents-reveal flex flex-col justify-between gap-7 border-b border-[#ded7d0] pb-9 md:flex-row md:items-end" style={{ "--i": 0 } as CSSProperties}><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#ff3c00]">FLEET / REGISTRY</p><h1 className="mt-4 text-[clamp(3rem,6vw,5.5rem)] font-semibold leading-[.86] tracking-[-.045em]">Agents</h1><p className="mt-5 max-w-[440px] text-[14px] leading-[1.45] text-[#776f68]">The wallets that act for Helix-DAO, each with a doctrine, a limit, and a legible trail.</p></div><button type="button" onClick={() => setDeployOpen(true)} className="warm-pill group w-fit rounded-full bg-[#ff3c00] px-5 py-3 text-[11px] font-semibold text-white">Deploy governed wallet<Arrow /></button></div>
    <section className="flex flex-wrap items-center gap-x-5 gap-y-3 border-b border-[#ded7d0] py-5 font-mono text-[9px] uppercase tracking-[.14em] text-[#837a72]"><span>TOTAL <b className="font-normal text-[#292522]">12</b></span><span className="h-4 w-px bg-[#ded7d0]" /><span>ACTIVE <b className="font-normal text-[#292522]">9</b></span><span className="h-4 w-px bg-[#ded7d0]" /><span>UNDER RESTRAINT <b className="font-normal text-[#ff3c00]">2</b></span><span className="h-4 w-px bg-[#ded7d0]" /><span>IDLE <b className="font-normal text-[#292522]">1</b></span></section>
    <section className="flex flex-col justify-between gap-4 py-7 sm:flex-row sm:items-center"><div className="flex flex-wrap gap-2">{(["ALL", "ACTIVE", "FROZEN", "IDLE"] as const).map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`rounded-full px-3.5 py-2 font-mono text-[9px] uppercase tracking-[.14em] transition-colors ${filter === item ? "bg-[#292522] text-[#faf6f1]" : "border border-[#ded7d0] text-[#837a72] hover:border-[#292522] hover:text-[#292522]"}`}>{item}</button>)}</div><label className="flex items-center gap-2 rounded-full border border-[#ded7d0] px-4 py-2.5 text-[#837a72] focus-within:border-[#292522]"><span className="font-mono text-[10px]">⌕</span><input aria-label="Search agents" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search agents" className="w-[170px] bg-transparent text-[12px] outline-none placeholder:text-[#9b9289]" /></label></section>
    <section className="grid gap-10 xl:grid-cols-[minmax(0,1.65fr)_minmax(330px,.75fr)]"><div className="agents-reveal" style={{ "--i": 2 } as CSSProperties}><div className="flex items-end justify-between border-b border-[#ded7d0] pb-4"><div><p className="font-mono text-[10px] uppercase tracking-[.17em] text-[#ff3c00]">REGISTRY / {visibleAgents.length.toString().padStart(2, "0")}</p><h2 className="mt-2 text-[22px] font-medium tracking-[-.045em]">Agent register</h2></div><span className="hidden font-mono text-[9px] uppercase tracking-[.13em] text-[#9b9289] md:inline">policy/v4.18</span></div><div className="hidden grid-cols-[.9fr_1.35fr_1fr_1fr_1.1fr_1.3fr] gap-3 border-b border-[#ded7d0] px-3 py-3 font-mono text-[9px] uppercase tracking-[.13em] text-[#9b9289] md:grid"><span>Status</span><span>Agent</span><span>Posture</span><span>Daily spend</span><span>Categories</span><span>Last event</span></div><div className="divide-y divide-[#e3dcd5]">{visibleAgents.map((agent, i) => { const status = frozen.includes(agent.name) ? "FROZEN" : agent.status; return <button type="button" key={agent.name} onClick={() => setSelected(agent.name)} style={{ "--i": i + 3 } as CSSProperties} className={`agent-row agents-reveal grid w-full gap-3 px-3 py-5 text-left md:grid-cols-[.9fr_1.35fr_1fr_1fr_1.1fr_1.3fr] md:items-center ${selected === agent.name ? "bg-[#f5f0ea] shadow-[inset_2px_0_0_#ff3c00]" : ""}`}><div><StatusPill status={status} /></div><div><p className="text-[13px] font-medium"><a data-nav="AGENT_DETAIL" href="#agent-detail" onClick={(event) => event.stopPropagation()} className="transition-colors hover:text-[#ff3c00]">{agent.name}</a></p><p className="mt-1 font-mono text-[9px] text-[#9b9289]">{agent.wallet}</p></div><div><div className="flex items-center justify-between font-mono text-[10px] tabular-nums"><span>{agent.posture}/100</span><span className="text-[#9b9289]">posture</span></div><div className="meter mt-2 w-full max-w-[90px]"><span style={{ transform: `scaleX(${agent.posture / 100})` }} /></div></div><div><span className="font-mono text-[11px] tabular-nums">{agent.spend}</span><span className="block mt-1 font-mono text-[9px] text-[#9b9289]">of {agent.cap}</span></div><div className="flex flex-wrap gap-1">{agent.categories.map((category) => <span key={category} className="rounded-full border border-[#ded7d0] px-2 py-1 font-mono text-[8px] uppercase tracking-[.1em] text-[#837a72]">{category}</span>)}</div><div><p className="text-[11px] text-[#655d56]">{agent.event}</p><p className="mt-1 font-mono text-[9px] text-[#9b9289]">{agent.eventTime}</p></div></button>; })}</div>{visibleAgents.length === 0 && <div className="border-b border-[#ded7d0] py-16 text-center"><p className="font-mono text-[10px] uppercase tracking-[.14em] text-[#837a72]">No agents match this view</p><button type="button" onClick={() => { setFilter("ALL"); setQuery(""); }} className="mt-4 text-[12px] text-[#ff3c00] underline underline-offset-4">Clear filters</button></div>}</div>
      <aside className="agents-reveal bg-[#f5f0ea] p-6 md:p-7" style={{ "--i": 3 } as CSSProperties}><div className="flex items-start justify-between border-b border-[#ded7d0] pb-5"><div><p className="font-mono text-[10px] uppercase tracking-[.17em] text-[#ff3c00]">SELECTED WALLET</p><h2 className="mt-2 text-[22px] font-medium tracking-[-.045em]">{selectedAgent.name}</h2></div><StatusPill status={selectedStatus} /></div><div className="border-b border-[#ded7d0] py-6"><p className="font-mono text-[9px] uppercase tracking-[.14em] text-[#837a72]">DOCTRINE SNAPSHOT</p><p className="mt-3 text-[13px] leading-[1.5] text-[#655d56]">{selectedAgent.doctrine}</p><p className="mt-4 font-mono text-[9px] text-[#9b9289]">{selectedAgent.wallet} · USDC</p></div><div className="grid grid-cols-2 gap-y-5 border-b border-[#ded7d0] py-6"><div><p className="font-mono text-[9px] uppercase tracking-[.12em] text-[#837a72]">PER TX CAP</p><p className="mt-2 font-mono text-[13px]">$500.00</p></div><div><p className="font-mono text-[9px] uppercase tracking-[.12em] text-[#837a72]">DAILY CAP</p><p className="mt-2 font-mono text-[13px]">{selectedAgent.cap}</p></div><div><p className="font-mono text-[9px] uppercase tracking-[.12em] text-[#837a72]">POSTURE</p><p className="mt-2 font-mono text-[13px]">{selectedAgent.posture} / 100</p></div><div><p className="font-mono text-[9px] uppercase tracking-[.12em] text-[#837a72]">NETWORK</p><p className="mt-2 font-mono text-[13px]">ARC TESTNET</p></div></div><div className="py-6"><p className="font-mono text-[9px] uppercase tracking-[.14em] text-[#837a72]">RECENT DECISIONS</p><div className="mt-4 space-y-3">{selectedAgent.decisions.map((item) => <div key={item} className="flex items-center justify-between gap-3 text-[11px] text-[#655d56]"><span>{item.split(" · ")[0]} · {item.split(" · ")[1]}</span><span className={`font-mono text-[8px] tracking-[.1em] ${item.endsWith("REJECTED") ? "text-[#ff3c00]" : item.endsWith("ESCALATED") ? "text-[#ff3c00]" : "text-[#3f653e]"}`}>{item.split(" · ").slice(-1)[0]}</span></div>)}</div></div><div className="flex gap-2 border-t border-[#ded7d0] pt-5"><button type="button" onClick={toggleFreeze} className="warm-pill warm-pill-ghost rounded-full border border-[#ded7d0] px-4 py-2.5 text-[11px] font-semibold">{selectedStatus === "FROZEN" ? "Unfreeze" : "Freeze"}</button><button type="button" data-nav="POLICY_EDITOR" className="warm-pill group rounded-full bg-[#ff3c00] px-4 py-2.5 text-[11px] font-semibold text-white">Edit policy<Arrow /></button></div></aside></section>
    <footer className="mt-14 flex flex-col justify-between gap-4 border-t border-[#ded7d0] pt-5 text-[11px] text-[#837a72] sm:flex-row"><span className="font-mono uppercase tracking-[.14em]">12 governed wallets · 9 active now</span><span>Last registry sync 2 minutes ago</span></footer>
   </div>{deployOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[rgba(41,37,34,.16)] p-5" role="dialog" aria-modal="true" onClick={() => setDeployOpen(false)} onKeyDown={(event) => event.key === "Escape" && setDeployOpen(false)}><div className="w-full max-w-[480px] border border-[#cfc5bc] bg-[#faf6f1] p-7 shadow-[12px_14px_0_#e7e0d9]" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#ff3c00]">FLEET / NEW WALLET</p><h2 className="mt-4 text-[28px] font-semibold tracking-[-.05em]">Deploy governed wallet</h2></div><button type="button" onClick={() => setDeployOpen(false)} className="font-mono text-[10px] text-[#837a72]">CLOSE</button></div><label className="mt-8 block"><span className="font-mono text-[9px] uppercase tracking-[.14em] text-[#837a72]">WALLET NAME</span><input autoFocus value={walletName} onChange={(event) => setWalletName(event.target.value)} placeholder="e.g. billing-agent" className="mt-2 w-full border-b border-[#bdb4aa] bg-transparent py-3 text-[15px] outline-none focus:border-[#ff3c00]" /></label><label className="mt-6 block"><span className="font-mono text-[9px] uppercase tracking-[.14em] text-[#837a72]">DOCTRINE TEMPLATE</span><select className="mt-2 w-full border-b border-[#bdb4aa] bg-transparent py-3 text-[14px] outline-none"><option>Procurement / standard caps</option><option>Research / human escalation</option></select></label><p className="mt-5 font-mono text-[9px] leading-[1.6] text-[#9b9289]">A fresh wallet starts frozen. Publish a policy before it can move capital.</p><div className="mt-8 flex justify-end gap-3"><button type="button" onClick={() => setDeployOpen(false)} className="warm-pill warm-pill-ghost rounded-full border border-[#ded7d0] px-4 py-2.5 text-[11px]">Cancel</button><button type="button" disabled={!walletName.trim()} onClick={() => setDeployOpen(false)} className="warm-pill rounded-full bg-[#ff3c00] px-4 py-2.5 text-[11px] text-white disabled:opacity-40">Create wallet</button></div></div></div>}</Shell>;
}

export { Agents };
export default Agents;