import { useState } from "react";

const records = [
  ["09:41:08", "AWS", "$184.20", "ALLOWED", "0x0ba4…91c2"],
  ["09:34:05", "AWS Bedrock", "$316.40", "ALLOWED", "0x2f88…a102"],
  ["17 Jun · 16:12", "OpenAI", "$212.80", "ALLOWED", "0x8d13…c440"],
  ["17 Jun · 14:08", "AWS", "$48.00", "ALLOWED", "0x6a71…e8b3"],
];

export function Explorer() {
  const [copied, setCopied] = useState(false);
  const copy = () => { if (navigator.clipboard) void navigator.clipboard.writeText("0x3f81c4…9a2c"); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  return <main className="min-h-[100dvh] bg-[#faf6f1] text-[#292522]" style={{ fontFamily: "'Inter Tight', sans-serif" }}><style>{`@import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Inter+Tight:wght@400;500;600;700&display=swap');.font-mono{font-family:'DM Mono',monospace}@keyframes enter{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}.enter{animation:enter 440ms cubic-bezier(.16,1,.3,1) both}@media(prefers-reduced-motion:reduce){.enter{animation:none}}`}</style>
    <nav className="flex items-center justify-between border-b border-[#ded7d0] px-5 py-5 md:px-9"><button type="button" data-nav="LANDING" className="text-[18px] font-bold tracking-[-.07em]">ARCANUM<span className="text-[#ff3c00]">.</span></button><div className="flex items-center gap-4"><span className="hidden font-mono text-[9px] uppercase tracking-[.16em] text-[#9b9289] sm:inline">PUBLIC EXPLORER</span><button type="button" data-nav="BADGE" className="rounded-full border border-[#ded7d0] px-4 py-2 font-mono text-[9px] tracking-[.12em] transition hover:border-[#292522]">GET BADGE ↗</button></div></nav>
    <div className="mx-auto max-w-[1120px] px-5 py-10 md:px-9 md:py-16"><header className="enter border-b border-[#ded7d0] pb-10"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[#ff3c00]">ARC / PUBLIC VERIFICATION</p><div className="mt-5 flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><h1 className="text-[clamp(3rem,7vw,6rem)] font-semibold leading-[.84] tracking-[-.09em]">procurement-bot</h1><p className="mt-5 max-w-[500px] text-[14px] leading-[1.5] text-[#655d56]">A governed autonomous wallet operated by HELIX-DAO. Anyone can verify its doctrine and public spend.</p></div><span className="flex w-fit items-center gap-2 rounded-full bg-[#e7f0e5] px-3 py-2 font-mono text-[9px] tracking-[.12em] text-[#3f653e]"><span className="h-1.5 w-1.5 rounded-full bg-[#4d7b49]" /> GOVERNED / ACTIVE</span></div></header>
      <section className="enter grid border-b border-[#ded7d0] md:grid-cols-[1.15fr_.85fr]" style={{ animationDelay: "100ms" }}><div className="py-8 md:pr-10"><p className="font-mono text-[9px] uppercase tracking-[.16em] text-[#9b9289]">WALLET IDENTITY</p><div className="mt-4 flex items-center gap-3"><code className="font-mono text-[15px]">0x3f81c4…9a2c</code><button type="button" onClick={copy} className="rounded-full border border-[#ded7d0] px-3 py-1.5 font-mono text-[9px] transition hover:border-[#292522]">{copied ? "COPIED" : "COPY"}</button></div><p className="mt-4 font-mono text-[9px] uppercase tracking-[.12em] text-[#837a72]">ARC TESTNET · USDC · FIRST SEEN 04 JUN 2025</p></div><div className="border-l border-[#ded7d0] py-8 pl-7"><p className="font-mono text-[9px] uppercase tracking-[.16em] text-[#9b9289]">GOVERNANCE PROOF</p><p className="mt-4 text-[19px] font-medium tracking-[-.04em]">Policy v4.18 is active.</p><p className="mt-2 text-[12px] leading-[1.5] text-[#655d56]">Vendors, caps, and every decision are recorded by ARCANUM.</p><button type="button" data-nav="BADGE" className="mt-5 font-mono text-[9px] uppercase tracking-[.13em] text-[#ff3c00] underline underline-offset-4">Use this proof on your site ↗</button></div></section>
      <section className="enter pt-10" style={{ animationDelay: "180ms" }}><div className="flex items-end justify-between border-b border-[#ded7d0] pb-4"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#ff3c00]">PUBLIC LEDGER / 04 RECORDS</p><h2 className="mt-2 text-[23px] font-medium tracking-[-.045em]">Recent governed spend</h2></div><span className="font-mono text-[9px] text-[#9b9289]">UTC · READ ONLY</span></div><div className="hidden grid-cols-[1fr_1.3fr_1fr_1fr_1.2fr] gap-4 border-b border-[#ded7d0] px-3 py-3 font-mono text-[9px] uppercase tracking-[.13em] text-[#9b9289] md:grid"><span>Time</span><span>Vendor</span><span>Amount</span><span>Verdict</span><span>Transaction</span></div><div className="divide-y divide-[#e3dcd5]">{records.map((r) => <div key={r[0]} className="grid gap-2 px-3 py-4 transition hover:translate-x-1 hover:bg-[#f5f0ea] md:grid-cols-[1fr_1.3fr_1fr_1fr_1.2fr] md:items-center"><span className="font-mono text-[10px] text-[#837a72]">{r[0]}</span><span className="text-[12px] font-medium">{r[1]}</span><span className="font-mono text-[12px] tabular-nums">{r[2]}</span><span className="w-fit rounded-full bg-[#e7f0e5] px-2.5 py-1 font-mono text-[9px] tracking-[.12em] text-[#3f653e]">{r[3]}</span><span className="font-mono text-[10px] text-[#837a72]">{r[4]}</span></div>)}</div></section>
      <footer className="mt-14 flex flex-wrap justify-between gap-4 border-t border-[#ded7d0] pt-5 font-mono text-[9px] uppercase tracking-[.12em] text-[#9b9289]"><span>ARCANUM · PUBLIC READ MODEL</span><span>Policy/v4.18 · updated 09:42:11 UTC</span></footer>
    </div></main>;
}