import { useState, type CSSProperties, type ReactNode } from "react";
import { Header } from "./_shared/Header";

function Shell({ children }: { children: ReactNode }) {
  return <main className="min-h-[100dvh] bg-[var(--wl-bg)] text-[var(--wl-ink)]" style={{ fontFamily: "'Inter Tight',sans-serif" }}><style>{`
    @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Inter+Tight:wght@400;500;600;700&display=swap');.font-mono{font-family:'DM Mono',monospace}.policy-in{animation:policyIn 560ms cubic-bezier(.16,1,.3,1) calc(var(--i,0)*80ms) both}@keyframes policyIn{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:none}}.warm-pill{position:relative;isolation:isolate;overflow:hidden;transition:transform 220ms cubic-bezier(.16,1,.3,1),box-shadow 320ms ease,color 220ms ease}.warm-pill:before{content:"";position:absolute;inset:0;z-index:-1;background:var(--wl-signal-deep);transform:translateY(102%);transition:transform 320ms cubic-bezier(.16,1,.3,1)}.warm-pill:hover{transform:translateY(-1px);box-shadow:0 10px 28px -8px rgba(var(--wl-signal-rgb),.4)}.warm-pill:hover:before{transform:translateY(0)}.warm-ghost:before{background:var(--wl-ink)}.warm-ghost:hover{color:var(--wl-bg)}.policy-input{border-bottom:1px solid var(--wl-faint);background:transparent;padding:10px 0;font-family:'DM Mono',monospace;font-size:13px;outline:none;transition:border-color 220ms ease}.policy-input:focus{border-color:var(--wl-signal)}@media(prefers-reduced-motion:reduce){.policy-in,.warm-pill,.warm-pill:before{animation:none;transition:none}}
  `}</style><Header active="AGENTS" />{children}</main>;
}

export function PolicyEditor() {
  const [daily, setDaily] = useState("5000");
  const [perTx, setPerTx] = useState("500");
  const [threshold, setThreshold] = useState("1000");
  const [vendors, setVendors] = useState(["AWS", "AWS Bedrock", "OpenAI"]);
  const [saved, setSaved] = useState<"clean" | "saved" | "deployed">("clean");
  const toggleVendor = (vendor: string) => setVendors((current) => current.includes(vendor) ? current.filter((item) => item !== vendor) : [...current, vendor]);
  const save = () => { setSaved("saved"); window.setTimeout(() => setSaved("clean"), 2600); };
  return <Shell><div className="mx-auto max-w-[1400px] px-5 py-9 md:px-8 md:py-10">
    <div className="policy-in flex flex-col justify-between gap-7 border-b border-[var(--wl-line)] pb-9 md:flex-row md:items-end" style={{ "--i": 0 } as CSSProperties}><div><button type="button" data-nav="AGENT_DETAIL" className="font-mono text-[9px] uppercase tracking-[.16em] text-[var(--wl-secondary)] hover:text-[var(--wl-signal)]">← procurement-bot dossier</button><p className="mt-6 font-mono text-[10px] uppercase tracking-[.18em] text-[var(--wl-signal)]">GOVERNANCE / POLICY INSTRUMENT</p><h1 className="mt-4 text-[clamp(2.8rem,6vw,5.3rem)] font-semibold leading-[.86] tracking-[-.045em]">Policy editor</h1><p className="mt-5 max-w-[520px] text-[14px] leading-[1.45] text-[var(--wl-secondary2)]">Revise the governing document for procurement-bot. Changes remain inert until a human operator signs and deploys them.</p></div><div className="flex items-center gap-3"><span className="font-mono text-[9px] uppercase tracking-[.13em] text-[var(--wl-secondary)]">DRAFT / REVISION 19</span><button type="button" onClick={save} className="warm-pill warm-ghost rounded-full border border-[var(--wl-line)] px-4 py-2.5 text-[11px] font-semibold">Save draft</button><button type="button" onClick={() => setSaved("deployed")} className="warm-pill rounded-full bg-[var(--wl-signal)] px-5 py-3 text-[11px] font-semibold text-white">Sign & deploy</button></div></div>
    <div className="grid gap-10 pt-10 xl:grid-cols-[minmax(0,1.55fr)_360px]">
      <section className="policy-in border border-[var(--wl-line-bold)] bg-[var(--wl-bg-raised)] shadow-[14px_18px_0_var(--wl-bg-deep2)]" style={{ "--i": 1 } as CSSProperties}><div className="border-b border-[var(--wl-line)] px-6 py-6 md:px-9"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[var(--wl-signal)]">ARCANUM / GOVERNING DOCUMENT</p><h2 className="mt-3 text-[28px] font-semibold tracking-[-.05em]">Procurement doctrine</h2></div><span className="border border-[var(--wl-line)] px-2 py-1 font-mono text-[9px] uppercase tracking-[.12em] text-[var(--wl-secondary)]">v4.19 draft</span></div><p className="mt-4 max-w-[570px] text-[13px] leading-[1.5] text-[var(--wl-body)]">This instrument defines where capital may move, how much may move, and when a person must take the seat.</p></div>
        <div className="divide-y divide-[var(--wl-line-soft)] px-6 md:px-9"><div className="py-7"><p className="font-mono text-[10px] uppercase tracking-[.15em] text-[var(--wl-signal)]">01 / LIMITS</p><h3 className="mt-2 text-[18px] font-medium">Capital envelope</h3><div className="mt-6 grid gap-7 sm:grid-cols-3"><label><span className="font-mono text-[9px] uppercase tracking-[.12em] text-[var(--wl-secondary)]">PER TRANSACTION · USDC</span><input className="policy-input mt-1 w-full" value={perTx} onChange={(e) => setPerTx(e.target.value)} /></label><label><span className="font-mono text-[9px] uppercase tracking-[.12em] text-[var(--wl-secondary)]">DAILY CAP · USDC</span><input className="policy-input mt-1 w-full" value={daily} onChange={(e) => setDaily(e.target.value)} /></label><label><span className="font-mono text-[9px] uppercase tracking-[.12em] text-[var(--wl-secondary)]">WEEKLY CAP · USDC</span><input className="policy-input mt-1 w-full" defaultValue="18000" /></label></div></div>
          <div className="py-7"><p className="font-mono text-[10px] uppercase tracking-[.15em] text-[var(--wl-signal)]">02 / COUNTERPARTIES</p><h3 className="mt-2 text-[18px] font-medium">Allowed vendors</h3><div className="mt-5 flex flex-wrap gap-2">{["AWS","AWS Bedrock","OpenAI","Anthropic","Qdrant Cloud"].map(v=><button type="button" key={v} onClick={() => toggleVendor(v)} className={`rounded-full border px-3.5 py-2 font-mono text-[9px] uppercase tracking-[.1em] transition-colors ${vendors.includes(v) ? "border-[var(--wl-ink)] bg-[var(--wl-ink)] text-[var(--wl-bg)]" : "border-[var(--wl-line)] text-[var(--wl-secondary)] hover:border-[var(--wl-ink)]"}`}>{vendors.includes(v) ? "✓ " : "+ "}{v}</button>)}</div><p className="mt-4 font-mono text-[9px] text-[var(--wl-mute)]">{vendors.length} destinations permitted · all other counterparties are blocked</p></div>
          <div className="py-7"><p className="font-mono text-[10px] uppercase tracking-[.15em] text-[var(--wl-signal)]">03 / HUMAN CONTROL</p><h3 className="mt-2 text-[18px] font-medium">Escalation thresholds</h3><div className="mt-6 grid gap-7 sm:grid-cols-2"><label><span className="font-mono text-[9px] uppercase tracking-[.12em] text-[var(--wl-secondary)]">ESCALATE ABOVE · USDC</span><input className="policy-input mt-1 w-full" value={threshold} onChange={(e) => setThreshold(e.target.value)} /></label><label><span className="font-mono text-[9px] uppercase tracking-[.12em] text-[var(--wl-secondary)]">QUORUM REQUIRED</span><select className="policy-input mt-1 w-full"><option>2 of 3 approvers</option><option>1 of 2 approvers</option></select></label></div><div className="mt-6 space-y-3 text-[12px] text-[var(--wl-body)]"><label className="flex items-center gap-3"><input type="checkbox" defaultChecked className="accent-[var(--wl-signal)]" /> Require human approval for new vendors</label><label className="flex items-center gap-3"><input type="checkbox" defaultChecked className="accent-[var(--wl-signal)]" /> Freeze wallet after 3 rejected attempts</label></div></div>
        </div><div className="flex flex-col justify-between gap-3 border-t border-[var(--wl-line)] bg-[var(--wl-bg-soft)] px-6 py-5 sm:flex-row sm:items-center md:px-9"><p className="font-mono text-[9px] uppercase tracking-[.12em] text-[var(--wl-secondary)]">Unsaved changes are local to this draft</p><div className="flex gap-2"><button type="button" onClick={() => { setDaily("5000"); setPerTx("500"); setThreshold("1000"); }} className="rounded-full px-3 py-2 font-mono text-[9px] uppercase tracking-[.12em] text-[var(--wl-secondary)] hover:text-[var(--wl-ink)]">Reset</button><button type="button" onClick={save} className="warm-pill rounded-full bg-[var(--wl-signal)] px-4 py-2.5 text-[10px] font-semibold text-white">Save revision</button></div></div></section>
      <aside className="policy-in bg-[var(--wl-bg-soft)] p-6 md:p-7" style={{ "--i": 2 } as CSSProperties}><div className="flex items-start justify-between border-b border-[var(--wl-line)] pb-5"><div><p className="font-mono text-[10px] uppercase tracking-[.17em] text-[var(--wl-signal)]">SIGNING / CONTROL</p><h2 className="mt-2 text-[22px] font-medium tracking-[-.045em]">Deployment record</h2></div><span className={`rounded-full px-2.5 py-1 font-mono text-[9px] tracking-[.12em] ${saved === "deployed" ? "bg-[var(--wl-green-tint)] text-[var(--wl-green)]" : "border border-[var(--wl-signal)] text-[var(--wl-signal)]"}`}>{saved === "deployed" ? "DEPLOYED" : saved === "saved" ? "SAVED" : "PENDING"}</span></div><dl className="divide-y divide-[var(--wl-line)] py-3 font-mono text-[10px]">{[["AGENT", "procurement-bot"],["CURRENT", "v4.18 · active"],["PROPOSED", "v4.19 · draft"],["SIGNER", "HD / HELIX-DAO"],["NETWORK", "ARC TESTNET"]].map(([l,v])=><div key={l} className="grid grid-cols-[.9fr_1.1fr] gap-3 py-3"><dt className="text-[var(--wl-mute)]">{l}</dt><dd className="text-right text-[var(--wl-body)]">{v}</dd></div>)}</dl><div className="border-t border-[var(--wl-line)] py-6"><p className="font-mono text-[9px] uppercase tracking-[.14em] text-[var(--wl-secondary)]">EFFECT OF SIGNATURE</p><p className="mt-3 text-[13px] leading-[1.5] text-[var(--wl-body)]">The new limits become authoritative for the next governed event. Existing pending decisions retain their original policy version.</p></div><div className="border-t border-[var(--wl-line)] pt-5"><button type="button" data-nav="AGENT_DETAIL" className="group font-mono text-[10px] uppercase tracking-[.13em] text-[var(--wl-body)] hover:text-[var(--wl-signal)]">Return to dossier<span className="ml-2 transition-transform group-hover:-translate-x-1">←</span></button></div></aside>
    </div><footer className="mt-14 flex flex-col justify-between gap-3 border-t border-[var(--wl-line)] pt-5 font-mono text-[9px] uppercase tracking-[.13em] text-[var(--wl-mute)] sm:flex-row"><span>Draft changes · no capital movement until signed</span><span>{saved === "deployed" ? "Revision v4.19 deployed · 09:48 UTC" : "Last deployed v4.18 · 08:12 UTC"}</span></footer>
  </div></Shell>;
}

export default PolicyEditor;