import { useState, type CSSProperties, type ReactNode } from "react";
import { Header } from "./_shared/Header";

function Shell({ children }: { children: ReactNode }) {
  return <main className="min-h-[100dvh] bg-[#faf6f1] text-[#292522]" style={{ fontFamily: "'Inter Tight',sans-serif" }}><style>{`
    @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Inter+Tight:wght@400;500;600;700&display=swap');.font-mono{font-family:'DM Mono',monospace}.policy-in{animation:policyIn 560ms cubic-bezier(.16,1,.3,1) calc(var(--i,0)*80ms) both}@keyframes policyIn{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:none}}.warm-pill{position:relative;isolation:isolate;overflow:hidden;transition:transform 220ms cubic-bezier(.16,1,.3,1),box-shadow 320ms ease,color 220ms ease}.warm-pill:before{content:"";position:absolute;inset:0;z-index:-1;background:#d63200;transform:translateY(102%);transition:transform 320ms cubic-bezier(.16,1,.3,1)}.warm-pill:hover{transform:translateY(-1px);box-shadow:0 10px 28px -8px rgba(255,60,0,.4)}.warm-pill:hover:before{transform:translateY(0)}.warm-ghost:before{background:#292522}.warm-ghost:hover{color:#faf6f1}.policy-input{border-bottom:1px solid #bdb4aa;background:transparent;padding:10px 0;font-family:'DM Mono',monospace;font-size:13px;outline:none;transition:border-color 220ms ease}.policy-input:focus{border-color:#ff3c00}@media(prefers-reduced-motion:reduce){.policy-in,.warm-pill,.warm-pill:before{animation:none;transition:none}}
  `}</style><Header active="AGENTS" />{children}</main>;
}

export function PolicyEditor() {
  const [daily, setDaily] = useState("5000");
  const [perTx, setPerTx] = useState("500");
  const [threshold, setThreshold] = useState("1000");
  const [vendors, setVendors] = useState(["AWS", "AWS Bedrock", "OpenAI"]);
  const [saved, setSaved] = useState<"clean" | "saved" | "deployed">("clean");
  const toggleVendor = (vendor: string) => setVendors((current) => current.includes(vendor) ? current.filter((item) => item !== vendor) : [...current, vendor]);
  const save = () => { setSaved("saved"); window.setTimeout(() => setSaved("clean"), 2600); };
  return <Shell><div className="mx-auto max-w-[1400px] px-5 py-9 md:px-8 md:py-10">
    <div className="policy-in flex flex-col justify-between gap-7 border-b border-[#ded7d0] pb-9 md:flex-row md:items-end" style={{ "--i": 0 } as CSSProperties}><div><button type="button" data-nav="AGENT_DETAIL" className="font-mono text-[9px] uppercase tracking-[.16em] text-[#837a72] hover:text-[#ff3c00]">← procurement-bot dossier</button><p className="mt-6 font-mono text-[10px] uppercase tracking-[.18em] text-[#ff3c00]">GOVERNANCE / POLICY INSTRUMENT</p><h1 className="mt-4 text-[clamp(2.8rem,6vw,5.3rem)] font-semibold leading-[.86] tracking-[-.085em]">Policy editor</h1><p className="mt-5 max-w-[520px] text-[14px] leading-[1.45] text-[#776f68]">Revise the governing document for procurement-bot. Changes remain inert until a human operator signs and deploys them.</p></div><div className="flex items-center gap-3"><span className="font-mono text-[9px] uppercase tracking-[.13em] text-[#837a72]">DRAFT / REVISION 19</span><button type="button" onClick={save} className="warm-pill warm-ghost rounded-full border border-[#ded7d0] px-4 py-2.5 text-[11px] font-semibold">Save draft</button><button type="button" onClick={() => setSaved("deployed")} className="warm-pill rounded-full bg-[#ff3c00] px-5 py-3 text-[11px] font-semibold text-white">Sign & deploy</button></div></div>
    <div className="grid gap-10 pt-10 xl:grid-cols-[minmax(0,1.55fr)_360px]">
      <section className="policy-in border border-[#cfc5bc] bg-[#fbf8f4] shadow-[14px_18px_0_#eee7df]" style={{ "--i": 1 } as CSSProperties}><div className="border-b border-[#ded7d0] px-6 py-6 md:px-9"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#ff3c00]">ARCANUM / GOVERNING DOCUMENT</p><h2 className="mt-3 text-[28px] font-semibold tracking-[-.06em]">Procurement doctrine</h2></div><span className="border border-[#ded7d0] px-2 py-1 font-mono text-[9px] uppercase tracking-[.12em] text-[#837a72]">v4.19 draft</span></div><p className="mt-4 max-w-[570px] text-[13px] leading-[1.5] text-[#655d56]">This instrument defines where capital may move, how much may move, and when a person must take the seat.</p></div>
        <div className="divide-y divide-[#e3dcd5] px-6 md:px-9"><div className="py-7"><p className="font-mono text-[10px] uppercase tracking-[.15em] text-[#ff3c00]">01 / LIMITS</p><h3 className="mt-2 text-[18px] font-medium">Capital envelope</h3><div className="mt-6 grid gap-7 sm:grid-cols-3"><label><span className="font-mono text-[9px] uppercase tracking-[.12em] text-[#837a72]">PER TRANSACTION · USDC</span><input className="policy-input mt-1 w-full" value={perTx} onChange={(e) => setPerTx(e.target.value)} /></label><label><span className="font-mono text-[9px] uppercase tracking-[.12em] text-[#837a72]">DAILY CAP · USDC</span><input className="policy-input mt-1 w-full" value={daily} onChange={(e) => setDaily(e.target.value)} /></label><label><span className="font-mono text-[9px] uppercase tracking-[.12em] text-[#837a72]">WEEKLY CAP · USDC</span><input className="policy-input mt-1 w-full" defaultValue="18000" /></label></div></div>
          <div className="py-7"><p className="font-mono text-[10px] uppercase tracking-[.15em] text-[#ff3c00]">02 / COUNTERPARTIES</p><h3 className="mt-2 text-[18px] font-medium">Allowed vendors</h3><div className="mt-5 flex flex-wrap gap-2">{["AWS","AWS Bedrock","OpenAI","Anthropic","Qdrant Cloud"].map(v=><button type="button" key={v} onClick={() => toggleVendor(v)} className={`rounded-full border px-3.5 py-2 font-mono text-[9px] uppercase tracking-[.1em] transition-colors ${vendors.includes(v) ? "border-[#292522] bg-[#292522] text-[#faf6f1]" : "border-[#ded7d0] text-[#837a72] hover:border-[#292522]"}`}>{vendors.includes(v) ? "✓ " : "+ "}{v}</button>)}</div><p className="mt-4 font-mono text-[9px] text-[#9b9289]">{vendors.length} destinations permitted · all other counterparties are blocked</p></div>
          <div className="py-7"><p className="font-mono text-[10px] uppercase tracking-[.15em] text-[#ff3c00]">03 / HUMAN CONTROL</p><h3 className="mt-2 text-[18px] font-medium">Escalation thresholds</h3><div className="mt-6 grid gap-7 sm:grid-cols-2"><label><span className="font-mono text-[9px] uppercase tracking-[.12em] text-[#837a72]">ESCALATE ABOVE · USDC</span><input className="policy-input mt-1 w-full" value={threshold} onChange={(e) => setThreshold(e.target.value)} /></label><label><span className="font-mono text-[9px] uppercase tracking-[.12em] text-[#837a72]">QUORUM REQUIRED</span><select className="policy-input mt-1 w-full"><option>2 of 3 approvers</option><option>1 of 2 approvers</option></select></label></div><div className="mt-6 space-y-3 text-[12px] text-[#655d56]"><label className="flex items-center gap-3"><input type="checkbox" defaultChecked className="accent-[#ff3c00]" /> Require human approval for new vendors</label><label className="flex items-center gap-3"><input type="checkbox" defaultChecked className="accent-[#ff3c00]" /> Freeze wallet after 3 rejected attempts</label></div></div>
        </div><div className="flex flex-col justify-between gap-3 border-t border-[#ded7d0] bg-[#f5f0ea] px-6 py-5 sm:flex-row sm:items-center md:px-9"><p className="font-mono text-[9px] uppercase tracking-[.12em] text-[#837a72]">Unsaved changes are local to this draft</p><div className="flex gap-2"><button type="button" onClick={() => { setDaily("5000"); setPerTx("500"); setThreshold("1000"); }} className="rounded-full px-3 py-2 font-mono text-[9px] uppercase tracking-[.12em] text-[#837a72] hover:text-[#292522]">Reset</button><button type="button" onClick={save} className="warm-pill rounded-full bg-[#ff3c00] px-4 py-2.5 text-[10px] font-semibold text-white">Save revision</button></div></div></section>
      <aside className="policy-in bg-[#f5f0ea] p-6 md:p-7" style={{ "--i": 2 } as CSSProperties}><div className="flex items-start justify-between border-b border-[#ded7d0] pb-5"><div><p className="font-mono text-[10px] uppercase tracking-[.17em] text-[#ff3c00]">SIGNING / CONTROL</p><h2 className="mt-2 text-[22px] font-medium tracking-[-.045em]">Deployment record</h2></div><span className={`rounded-full px-2.5 py-1 font-mono text-[9px] tracking-[.12em] ${saved === "deployed" ? "bg-[#e7f0e5] text-[#3f653e]" : "border border-[#ff3c00] text-[#ff3c00]"}`}>{saved === "deployed" ? "DEPLOYED" : saved === "saved" ? "SAVED" : "PENDING"}</span></div><dl className="divide-y divide-[#ded7d0] py-3 font-mono text-[10px]">{[["AGENT", "procurement-bot"],["CURRENT", "v4.18 · active"],["PROPOSED", "v4.19 · draft"],["SIGNER", "HD / HELIX-DAO"],["NETWORK", "ARC TESTNET"]].map(([l,v])=><div key={l} className="grid grid-cols-[.9fr_1.1fr] gap-3 py-3"><dt className="text-[#9b9289]">{l}</dt><dd className="text-right text-[#655d56]">{v}</dd></div>)}</dl><div className="border-t border-[#ded7d0] py-6"><p className="font-mono text-[9px] uppercase tracking-[.14em] text-[#837a72]">EFFECT OF SIGNATURE</p><p className="mt-3 text-[13px] leading-[1.5] text-[#655d56]">The new limits become authoritative for the next governed event. Existing pending decisions retain their original policy version.</p></div><div className="border-t border-[#ded7d0] pt-5"><button type="button" data-nav="AGENT_DETAIL" className="group font-mono text-[10px] uppercase tracking-[.13em] text-[#655d56] hover:text-[#ff3c00]">Return to dossier<span className="ml-2 transition-transform group-hover:-translate-x-1">←</span></button></div></aside>
    </div><footer className="mt-14 flex flex-col justify-between gap-3 border-t border-[#ded7d0] pt-5 font-mono text-[9px] uppercase tracking-[.13em] text-[#9b9289] sm:flex-row"><span>Draft changes · no capital movement until signed</span><span>{saved === "deployed" ? "Revision v4.19 deployed · 09:48 UTC" : "Last deployed v4.18 · 08:12 UTC"}</span></footer>
  </div></Shell>;
}

export default PolicyEditor;