import React, { useEffect, useState } from "react";
import "./CrystalCourt.css";

type Verdict = "ALLOWED" | "BLOCKED" | "ESCALATE";
type Row = { time:string; agent:string; vendor:string; amount:string; wallet:string; verdict:Verdict; rule:string };
const rows: Row[] = [
  {time:"09:41:08",agent:"procurement-bot",vendor:"AWS",amount:"$184.00",wallet:"0x3f…9a2c",verdict:"ALLOWED",rule:"daily cap · clear"},
  {time:"09:41:14",agent:"research-bot",vendor:"OpenAI",amount:"$68.40",wallet:"0x8c…41ef",verdict:"ALLOWED",rule:"allowlist · clear"},
  {time:"09:41:22",agent:"procurement-bot",vendor:"Anthropic",amount:"$920.00",wallet:"0x3f…9a2c",verdict:"BLOCKED",rule:"over $500 / tx cap"},
  {time:"09:41:27",agent:"ops-agent",vendor:"AWS",amount:"$1,200.00",wallet:"0xb1…77d0",verdict:"ESCALATE",rule:"human approval required"},
];

function Icon({name}:{name:"arrow"|"lock"|"check"|"shield"|"pulse"|"menu"}) {
  const paths = {arrow:<><path d="M5 12h13M13 6l6 6-6 6"/></>,lock:<><rect x="5" y="10" width="14" height="10" rx="1"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>,check:<path d="m5 12 4 4L19 6"/>,shield:<><path d="M12 3 20 7v5c0 5-3.4 8-8 9-4.6-1-8-4-8-9V7l8-4Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/></>,pulse:<path d="M3 12h4l2-6 4 12 2-6h6"/>,menu:<><path d="M4 7h16M4 12h16M4 17h16"/></>}[name];
  return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths}</svg>;
}
function Label({children}:{children:React.ReactNode}){return <p className="cc-mono mb-5 text-[10px] uppercase tracking-[.2em] text-[#718890]">{children}</p>}
function Verdict({value}:{value:Verdict}){const color=value==="BLOCKED"?"#a65349":value==="ESCALATE"?"#927039":"#4c7b67";return <span className="cc-mono inline-flex items-center gap-2 text-[9px] tracking-[.11em]" style={{color}}><i className="h-1.5 w-1.5 rounded-full bg-current"/>{value}</span>}
function Counter({to,prefix=""}:{to:number;prefix?:string}){const [n,setN]=useState(0);useEffect(()=>{let start=performance.now();let id=requestAnimationFrame(function tick(t){const p=Math.min((t-start)/1100,1);setN(Math.round(to*(1-Math.pow(1-p,3))));if(p<1)id=requestAnimationFrame(tick)});return()=>cancelAnimationFrame(id)},[to]);return <>{prefix}{n.toLocaleString()}</>}

export function CrystalCourt() {
  const [active,setActive]=useState(2), [menu,setMenu]=useState(false), [brief,setBrief]=useState(false);
  useEffect(()=>{const id=window.setInterval(()=>setActive(a=>(a+1)%rows.length),3000);return()=>window.clearInterval(id)},[]);
  const go=(id:string)=>{setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:"smooth"})};
  return <main className="cc-root min-h-[100dvh] overflow-hidden">
    <div className="cc-world relative">
      <span className="cc-orb cc-orb-a"/><span className="cc-orb cc-orb-b"/>
      <nav className="relative z-10 mx-auto flex max-w-[1240px] items-center justify-between px-6 py-6 lg:px-10">
        <button onClick={()=>go("top")} className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center border border-[#7695a0] text-sm">A</span><span className="cc-mono text-[12px] tracking-[.26em]">ARCANUM</span></button>
        <div className={`${menu?"flex":"hidden"} absolute left-6 right-6 top-20 flex-col gap-5 border border-white/70 bg-[#f4f2ea]/90 p-5 backdrop-blur-xl md:static md:flex md:flex-row md:items-center md:border-0 md:bg-transparent md:p-0 md:backdrop-blur-none`}>
          <button onClick={()=>go("governed")} className="cc-mono text-left text-[10px] uppercase tracking-[.16em] text-[#667b82] hover:text-[#172c35]">The ledger</button><button onClick={()=>go("policy")} className="cc-mono text-left text-[10px] uppercase tracking-[.16em] text-[#667b82] hover:text-[#172c35]">Policy layer</button><button onClick={()=>go("trust")} className="cc-mono text-left text-[10px] uppercase tracking-[.16em] text-[#667b82] hover:text-[#172c35]">Trust</button>
        </div>
        <div className="flex items-center gap-4"><button onClick={()=>setBrief(true)} className="cc-button hidden border border-[#294751] px-4 py-2.5 text-[10px] font-semibold uppercase tracking-[.12em] md:block">Request access <span className="ml-2">↗</span></button><button onClick={()=>setMenu(!menu)} className="md:hidden" aria-label="Open navigation"><Icon name="menu"/></button></div>
      </nav>
      <section id="top" className="mx-auto grid max-w-[1240px] gap-16 px-6 pb-24 pt-16 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-10 lg:pb-32 lg:pt-24">
        <div className="cc-reveal" style={{"--i":1} as React.CSSProperties}><Label>Non-custodial governance · Arc / USDC</Label><h1 className="cc-display max-w-[670px] text-[clamp(3.8rem,8vw,7.7rem)] font-medium leading-[.86] tracking-[-.065em]">Let the agent<br/><em className="text-[#6e909c]">move.</em><br/>Keep the word.</h1><p className="mt-9 max-w-[440px] text-[16px] leading-7 text-[#526c74]">ARCANUM puts a clear policy layer between an AI wallet and the world. Every dollar is checked, recorded, and answerable.</p><div className="mt-9 flex flex-wrap items-center gap-5"><button onClick={()=>setBrief(true)} className="cc-button flex items-center gap-4 bg-[#203f49] px-6 py-4 text-[11px] font-semibold uppercase tracking-[.12em] text-[#f3f0e8]">See the governed path <Icon name="arrow"/></button><span className="cc-mono text-[10px] text-[#74888e]"><Icon name="lock"/> <span className="ml-2 inline-block align-middle">No custody · Arc native</span></span></div></div>
        <div className="cc-reveal relative min-h-[510px]" style={{"--i":3} as React.CSSProperties}><div className="cc-glass absolute right-0 top-0 w-[88%] rotate-[2deg] p-5 sm:w-[80%]"><div className="flex justify-between border-b border-[#9cb1b5]/30 pb-4"><div><p className="cc-mono text-[9px] uppercase tracking-[.18em] text-[#789099]">Agent wallet policy</p><p className="cc-display mt-2 text-2xl">procurement-bot <span className="cc-mono text-xs text-[#789099]">/ v14</span></p></div><span className="cc-mono text-[9px] text-[#4c7b67]">● ACTIVE</span></div><div className="grid grid-cols-2 gap-0 pt-5"><div className="border-r border-[#9cb1b5]/30 pr-4"><p className="cc-mono text-[9px] uppercase tracking-[.12em] text-[#789099]">Per transaction</p><p className="cc-mono mt-5 text-4xl">$500</p><p className="mt-2 text-xs text-[#789099]">hard ceiling</p></div><div className="pl-5"><p className="cc-mono text-[9px] uppercase tracking-[.12em] text-[#789099]">Rolling 24h</p><p className="cc-mono mt-5 text-4xl">$5,000</p><p className="mt-2 text-xs text-[#789099]">daily velocity</p></div></div><div className="mt-8 border-t border-[#9cb1b5]/30 pt-5"><p className="cc-mono text-[9px] uppercase tracking-[.12em] text-[#789099]">Vendor allowlist</p><div className="mt-4 flex gap-2"><span className="border border-[#9cb1b5]/40 px-3 py-2 text-xs">AWS</span><span className="border border-[#9cb1b5]/40 px-3 py-2 text-xs">OpenAI</span><span className="border border-[#9cb1b5]/40 px-3 py-2 text-xs">+4</span></div></div></div><div className="cc-glass absolute bottom-4 left-0 w-[92%] -rotate-[2deg] p-5 shadow-[0_30px_70px_rgba(40,75,82,.18)]"><div className="flex items-center justify-between"><p className="cc-mono text-[9px] uppercase tracking-[.16em] text-[#789099]">Live governed ledger</p><span className="cc-mono text-[9px] text-[#4c7b67]"><i className="mr-2 inline-block h-1.5 w-1.5 rounded-full bg-current"/>streaming</span></div><div className="mt-4 grid grid-cols-[1fr_auto] gap-3 border-t border-[#9cb1b5]/30 pt-4"><div><p className="text-sm">{rows[active].agent} → {rows[active].vendor}</p><p className="cc-mono mt-1 text-[10px] text-[#789099]">{rows[active].time} UTC · {rows[active].wallet}</p></div><div className="text-right"><p className="cc-mono text-xl">{rows[active].amount}</p><Verdict value={rows[active].verdict}/></div></div></div></div>
      </section>
      <section className="border-y border-[#77939a]/20 bg-white/20"><div className="mx-auto grid max-w-[1240px] grid-cols-2 gap-y-8 px-6 py-7 lg:grid-cols-4 lg:px-10"><div><p className="cc-mono text-2xl"><Counter to={42}/>ms</p><p className="mt-2 text-[11px] text-[#73878d]">median policy check</p></div><div><p className="cc-mono text-2xl">$<Counter to={2400000}/></p><p className="mt-2 text-[11px] text-[#73878d]">governed this month</p></div><div><p className="cc-mono text-2xl"><Counter to={100}/>%</p><p className="mt-2 text-[11px] text-[#73878d]">ledger coverage</p></div><div><p className="cc-mono text-2xl"><Counter to={7}/></p><p className="mt-2 text-[11px] text-[#73878d]">active agent wallets</p></div></div></section>
    </div>
    <section id="governed" className="mx-auto max-w-[1240px] px-6 py-28 lg:px-10 lg:py-40"><div className="grid gap-12 lg:grid-cols-[.62fr_1.38fr]"><div className="cc-reveal"><Label>01 — How a dollar gets governed</Label><h2 className="cc-display text-5xl leading-[.95] tracking-[-.045em] md:text-6xl">Three doors.<br/><em className="text-[#6e909c]">One record.</em></h2><p className="mt-7 max-w-[310px] text-sm leading-6 text-[#60747b]">No opaque scoring. The operator’s intent is encoded as rules, then evaluated before settlement.</p></div><div className="grid gap-3"><div className="cc-glass flex items-start gap-5 p-6"><span className="cc-mono text-xs text-[#76949d]">01</span><div><h3 className="cc-display text-2xl">Policy check</h3><p className="mt-2 text-sm text-[#637980]">Caps, vendor identity, velocity and wallet context resolve in <span className="cc-mono text-xs">42ms</span>.</p></div><Icon name="pulse"/></div><div className="cc-glass flex items-start gap-5 p-6"><span className="cc-mono text-xs text-[#76949d]">02</span><div><h3 className="cc-display text-2xl">Allow or block</h3><p className="mt-2 text-sm text-[#637980]">A signed verdict reaches the Arc transaction before a dollar leaves the wallet.</p></div><Icon name="shield"/></div><div className="cc-glass flex items-start gap-5 p-6"><span className="cc-mono text-xs text-[#76949d]">03</span><div><h3 className="cc-display text-2xl">Escalate to a human</h3><p className="mt-2 text-sm text-[#637980]">Exceptions pause. An approver gets the exact context, not a notification-shaped mystery.</p></div><Icon name="lock"/></div></div></div></section>
    <section id="policy" className="bg-[#e5e7df]/65"><div className="mx-auto grid max-w-[1240px] gap-16 px-6 py-28 lg:grid-cols-[.75fr_1.25fr] lg:px-10 lg:py-36"><div><Label>02 — Policy layer</Label><h2 className="cc-display text-6xl leading-[.9] tracking-[-.05em]">The quiet<br/><em className="text-[#6e909c]">control plane.</em></h2><p className="mt-7 max-w-[350px] text-sm leading-6 text-[#60747b]">Finance writes the boundary. Engineering watches the system behave inside it. Agents keep their velocity.</p><button onClick={()=>setBrief(true)} className="cc-button mt-8 flex items-center gap-3 border border-[#385762] px-5 py-3 text-[10px] font-semibold uppercase tracking-[.15em]">Review a sample policy <Icon name="arrow"/></button></div><div className="cc-glass p-6 md:p-9"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-[#8ca5ab]/30 pb-6"><div><p className="cc-mono text-[9px] uppercase tracking-[.18em] text-[#789099]">Policy ID · ARC-POL-014</p><h3 className="cc-display mt-3 text-3xl">procurement-bot / production</h3></div><span className="cc-mono text-[9px] text-[#4c7b67]">SIGNED 09:39 UTC</span></div><div className="grid gap-0 md:grid-cols-2"><div className="border-b border-[#8ca5ab]/30 py-7 md:border-r md:pr-8"><p className="cc-mono text-[9px] uppercase tracking-[.15em] text-[#789099]">Limits</p><div className="mt-6 flex justify-between"><span className="text-sm">Per transaction</span><span className="cc-mono">$500</span></div><div className="mt-4 flex justify-between"><span className="text-sm">Rolling daily</span><span className="cc-mono">$5,000</span></div><div className="mt-4 flex justify-between"><span className="text-sm">Approval threshold</span><span className="cc-mono">$250</span></div></div><div className="border-b border-[#8ca5ab]/30 py-7 md:pl-8"><p className="cc-mono text-[9px] uppercase tracking-[.15em] text-[#789099]">Rules</p>{["Vendor allowlist · 07","Velocity · 24h window","Anomaly delta · 1.8σ"].map((x,i)=><div key={x} className="mt-5 flex items-center gap-3 text-sm"><span className="text-[#4c7b67]"><Icon name="check"/></span>{x}</div>)}</div></div><div className="pt-7"><p className="cc-mono text-[9px] uppercase tracking-[.15em] text-[#789099]">Settlement condition</p><p className="mt-3 text-sm leading-6 text-[#526c74]">Only settle when the policy hash and transaction intent agree. Otherwise: pause, surface, ask.</p></div></div></div></section>
    <section id="trust" className="mx-auto max-w-[1240px] px-6 py-28 lg:px-10 lg:py-36"><div className="grid items-end gap-14 lg:grid-cols-[1.15fr_.85fr]"><div><Label>03 — The trust surface</Label><h2 className="cc-display max-w-[670px] text-6xl leading-[.9] tracking-[-.055em] md:text-8xl">Nothing<br/><em className="text-[#6e909c]">disappears.</em></h2><p className="mt-8 max-w-[420px] text-[16px] leading-7 text-[#60747b]">Every decision leaves a durable trail: intent, policy version, verdict, signer, timestamp. Your audit starts before the money moves.</p></div><div className="cc-glass p-7"><div className="flex items-center justify-between"><p className="cc-mono text-[9px] uppercase tracking-[.16em] text-[#789099]">Audit stream / live</p><span className="cc-mono text-[9px] text-[#4c7b67]">UTC</span></div><div className="mt-6 space-y-5">{rows.map((r,i)=><div key={r.time} className={`cc-row flex items-start justify-between gap-3 border-t border-[#8ca5ab]/25 pt-4 ${i===active?"cc-verdict":""}`}><div><p className="text-xs">{r.agent} <span className="text-[#8aa0a5]">→ {r.vendor}</span></p><p className="cc-mono mt-1 text-[9px] text-[#82979d]">{r.time} · {r.rule}</p></div><div className="text-right"><p className="cc-mono text-xs">{r.amount}</p><Verdict value={r.verdict}/></div></div>)}</div><p className="cc-mono mt-7 border-t border-[#8ca5ab]/25 pt-5 text-[9px] text-[#82979d]">ledger hash · 0x83f2…d17c · block 18,409,221</p></div></div></section>
    <section className="cc-world border-y border-[#77939a]/20"><div className="mx-auto flex max-w-[1240px] flex-col justify-between gap-12 px-6 py-24 lg:flex-row lg:items-end lg:px-10 lg:py-32"><div><Label>Private briefing</Label><h2 className="cc-display max-w-[650px] text-6xl leading-[.88] tracking-[-.055em] md:text-8xl">Give the agent<br/><em className="text-[#6e909c]">room to work.</em></h2></div><div className="max-w-[320px]"><p className="text-sm leading-6 text-[#60747b]">Bring your wallet architecture. Leave with a governed path your finance team can sign.</p><button onClick={()=>setBrief(true)} className="cc-button mt-7 flex items-center gap-4 bg-[#203f49] px-6 py-4 text-[11px] font-semibold uppercase tracking-[.12em] text-[#f3f0e8]">Request access <Icon name="arrow"/></button></div></div></section>
    <footer className="mx-auto flex max-w-[1240px] flex-wrap items-center justify-between gap-6 px-6 py-9 lg:px-10"><div className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center border border-[#7695a0] text-xs">A</span><span className="cc-mono text-[11px] tracking-[.25em]">ARCANUM</span></div><p className="cc-mono text-[9px] uppercase tracking-[.14em] text-[#82979d]">Non-custodial governance for AI wallets · Arc / USDC</p><button onClick={()=>go("top")} className="cc-mono text-[9px] uppercase tracking-[.14em] text-[#60747b]">Back to top ↑</button></footer>
    {brief&&<div className="fixed inset-0 z-30 flex items-center justify-center bg-[#172c35]/25 p-6 backdrop-blur-sm"><div className="cc-glass max-w-md p-8"><button onClick={()=>setBrief(false)} className="float-right cc-mono text-xs" aria-label="Close">×</button><Label>Arcana / private access</Label><h2 className="cc-display text-4xl leading-none">A governed<br/><em className="text-[#6e909c]">conversation.</em></h2><p className="mt-5 text-sm leading-6 text-[#60747b]">Tell us where your agents spend today. We will return a policy map, not a sales sequence.</p><input className="mt-7 w-full border-b border-[#718d95]/50 bg-transparent px-0 py-3 text-sm outline-none placeholder:text-[#82979d]" placeholder="work email" /><button onClick={()=>setBrief(false)} className="cc-button mt-6 w-full bg-[#203f49] px-5 py-4 text-[10px] font-semibold uppercase tracking-[.14em] text-[#f3f0e8]">Send the brief ↗</button></div></div>}
    </main>
}