import React, { useEffect, useMemo, useState } from "react";

type Verdict = "ALLOWED" | "BLOCKED" | "ESCALATED";
type Tx = { time: string; agent: string; vendor: string; amount: string; address: string; verdict: Verdict; reason: string };

const transactions: Tx[] = [
  { time: "14:32:09", agent: "procurement-bot", vendor: "AWS", amount: "184.20", address: "0x3f…9a2c", verdict: "ALLOWED", reason: "under daily cap" },
  { time: "14:32:11", agent: "research-agent", vendor: "OpenAI", amount: "612.00", address: "0xa8…41d0", verdict: "BLOCKED", reason: "vendor not allowlisted" },
  { time: "14:32:14", agent: "procurement-bot", vendor: "Anthropic", amount: "420.00", address: "0x3f…9a2c", verdict: "ESCALATED", reason: "human approval required" },
  { time: "14:32:18", agent: "ops-runner", vendor: "AWS", amount: "76.40", address: "0x71…08be", verdict: "ALLOWED", reason: "policy matched" },
  { time: "14:32:22", agent: "research-agent", vendor: "AWS", amount: "38.90", address: "0xa8…41d0", verdict: "ALLOWED", reason: "under per-tx cap" },
];

function Reveal({ children, className = "", id }: { children: React.ReactNode; className?: string; id?: string }) {
  return <div id={id} className={`go-reveal ${className}`}>{children}</div>;
}

function VerdictPill({ verdict }: { verdict: Verdict }) {
  return <span className={`go-pill go-${verdict.toLowerCase()}`}><i />{verdict}</span>;
}

function Arrow() { return <span aria-hidden="true" className="go-arrow">↗</span>; }

export function GraphiteOps() {
  const [active, setActive] = useState(1);
  const [approved, setApproved] = useState(false);
  const [toast, setToast] = useState("");
  const [feature, setFeature] = useState<"policy" | "ledger" | "approval">("policy");
  const activeTx = useMemo(() => transactions[active], [active]);

  useEffect(() => {
    const timer = window.setInterval(() => setActive((value) => (value + 1) % transactions.length), 4200);
    return () => window.clearInterval(timer);
  }, []);

  const action = (message: string) => {
    setToast(message);
    window.setTimeout(() => setToast(""), 2400);
  };

  return (
    <main className="go-page">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&display=swap');
        :root { --go-bg:#0d1a2b; --go-panel:#12233a; --go-panel2:#172b45; --go-line:#263b55; --go-line2:#3a506a; --go-ink:#eee5d2; --go-muted:#b8bdc4; --go-dim:#8393a6; --go-sage:#c2a875; --go-warm:#d1bd91; }
        * { box-sizing:border-box; } html { scroll-behavior:smooth; } body { margin:0; background:var(--go-bg); }
        .go-page { color:var(--go-ink); background:var(--go-bg); min-height:100dvh; font-family:Manrope,sans-serif; overflow:hidden; }
        .go-page:before { content:""; position:fixed; inset:0; pointer-events:none; opacity:.028; background-image:url("data:image/svg+xml,%3Csvg width='72' height='72' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M0 0H72M0 0V72' fill='none' stroke='%23ffffff' stroke-opacity='.5'/%3E%3C/svg%3E"); }
        .go-wrap { max-width:1180px; margin:auto; padding:0 30px; } .go-mono { font-family:"DM Mono",monospace; font-variant-numeric:tabular-nums; }
        .go-nav { height:74px; display:flex; align-items:center; justify-content:space-between; border-bottom:1px solid var(--go-line); position:relative; z-index:2; }
        .go-logo { display:flex; align-items:center; gap:10px; color:#f4ead7; font-size:13px; letter-spacing:.22em; font-weight:800; } .go-logo i { width:7px; height:7px; display:block; background:var(--go-sage); border-radius:50%; }
        .go-navlinks { display:flex; align-items:center; gap:30px; } .go-navlinks a,.go-footer a { color:var(--go-muted); text-decoration:none; font-size:11px; transition:color .2s; } .go-navlinks a:hover,.go-footer a:hover { color:var(--go-ink); }
        button { font-family:inherit; } .go-button { cursor:pointer; border:1px solid var(--go-line2); color:var(--go-ink); background:#202429; padding:12px 16px; font-size:11px; font-weight:700; letter-spacing:.02em; transition:transform .2s,border-color .2s,background .2s; } .go-button:hover { transform:translateY(-2px); border-color:#77817b; background:#252a2b; } .go-button:active { transform:translateY(0); }
        .go-hero { min-height:650px; display:grid; grid-template-columns:42% 58%; gap:45px; align-items:center; border-bottom:1px solid var(--go-line); }
        .go-kicker,.go-eyebrow { color:var(--go-dim); font:500 10px "DM Mono",monospace; letter-spacing:.11em; text-transform:uppercase; } .go-kicker:before { content:""; display:inline-block; width:22px; border-top:1px solid var(--go-sage); vertical-align:middle; margin:0 9px 3px 0; }
        h1,h2,h3,p { margin:0; } .go-hero h1 { margin-top:26px; color:#f0f1ee; font-size:clamp(45px,5.4vw,74px); line-height:.99; letter-spacing:-.07em; font-weight:600; max-width:510px; } .go-hero h1 span { color:#7e8688; }
        .go-lead { color:#a4aaac; font-size:15px; line-height:1.75; max-width:440px; margin-top:28px; } .go-hero-actions { display:flex; gap:12px; align-items:center; margin-top:32px; } .go-quiet-link { color:var(--go-muted); font:11px "DM Mono",monospace; text-decoration:none; padding:12px 8px; transition:color .2s; } .go-quiet-link:hover { color:var(--go-ink); }
        .go-console { border:1px solid var(--go-line2); background:var(--go-panel); box-shadow:0 22px 60px rgba(0,0,0,.16); } .go-console-head { height:48px; display:flex; justify-content:space-between; align-items:center; padding:0 16px; border-bottom:1px solid var(--go-line); color:var(--go-dim); font:10px "DM Mono",monospace; } .go-live { color:var(--go-sage); } .go-live i { display:inline-block; width:6px; height:6px; background:var(--go-sage); border-radius:50%; margin-right:7px; }
        .go-console-meta { display:grid; grid-template-columns:repeat(3,1fr); border-bottom:1px solid var(--go-line); } .go-stat { padding:17px 16px; border-right:1px solid var(--go-line); } .go-stat:last-child { border-right:0; } .go-stat b { display:block; font:500 17px "DM Mono",monospace; color:#e1e4e2; } .go-stat span { display:block; color:var(--go-dim); font:9px "DM Mono",monospace; margin-top:7px; text-transform:uppercase; }
        .go-table-head,.go-row { display:grid; grid-template-columns:67px 1.2fr .8fr 85px 106px; gap:10px; align-items:center; } .go-table-head { padding:13px 16px 9px; color:var(--go-dim); font:9px "DM Mono",monospace; text-transform:uppercase; } .go-row { min-height:61px; padding:10px 16px; border-top:1px solid #25292d; transition:background .2s; } .go-row:hover,.go-row.active { background:#202429; } .go-cell { min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; } .go-cell small { display:block; color:var(--go-dim); font:9px "DM Mono",monospace; margin-top:5px; } .go-cell strong { color:#c8cdcc; font-size:11px; font-weight:600; } .go-amount { text-align:right; font:11px "DM Mono",monospace; color:#d8dcda; } .go-pill { display:inline-flex; align-items:center; gap:6px; font:9px "DM Mono",monospace; letter-spacing:.03em; } .go-pill i { display:block; width:5px; height:5px; border-radius:50%; background:var(--go-dim); } .go-allowed { color:#aab8ad; }.go-allowed i { background:#82958a; }.go-blocked { color:#b4a6a2; }.go-blocked i { background:#9b8178; }.go-escalated { color:#b3afa0; }.go-escalated i { background:#a69d7c; }
        .go-section { padding:135px 0; border-bottom:1px solid var(--go-line); } .go-section-grid { display:grid; grid-template-columns:30% 70%; gap:80px; } .go-section h2 { font-size:42px; line-height:1.04; letter-spacing:-.055em; font-weight:600; max-width:430px; } .go-section-intro { color:var(--go-muted); font-size:14px; line-height:1.75; max-width:390px; margin-top:21px; }
        .go-flow { display:grid; grid-template-columns:1fr 28px 1fr 28px 1fr; align-items:stretch; margin-top:12px; } .go-flow-step { border-top:1px solid var(--go-line2); padding:18px 0 0; min-height:145px; } .go-flow-step b { color:#dce0de; font-size:14px; font-weight:600; } .go-flow-step p { color:var(--go-muted); font-size:12px; line-height:1.6; margin-top:13px; max-width:170px; } .go-flow-num { color:var(--go-dim); font:10px "DM Mono",monospace; margin-bottom:30px; } .go-flow-arrow { color:var(--go-dim); padding-top:50px; text-align:center; }
        .go-feature { display:grid; grid-template-columns:1fr 1fr; gap:0; border:1px solid var(--go-line); } .go-feature-nav { border-right:1px solid var(--go-line); } .go-feature-tab { display:block; width:100%; cursor:pointer; text-align:left; color:var(--go-muted); background:transparent; border:0; border-bottom:1px solid var(--go-line); padding:24px; transition:background .2s,color .2s; } .go-feature-tab:last-child { border-bottom:0; } .go-feature-tab:hover,.go-feature-tab.active { background:#1b1f22; color:var(--go-ink); } .go-feature-tab b { display:block; font-size:13px; font-weight:600; } .go-feature-tab span { display:block; font:10px "DM Mono",monospace; color:var(--go-dim); margin-top:9px; } .go-feature-detail { padding:36px; min-height:250px; display:flex; flex-direction:column; justify-content:space-between; } .go-feature-detail h3 { font-size:27px; letter-spacing:-.04em; font-weight:600; } .go-feature-detail p { color:var(--go-muted); font-size:13px; line-height:1.7; max-width:360px; margin-top:15px; } .go-feature-detail code { color:var(--go-sage); font:11px "DM Mono",monospace; }
        .go-proof { display:grid; grid-template-columns:1.15fr .85fr; gap:100px; align-items:end; } .go-proof h2 { font-size:51px; max-width:560px; } .go-proof h2 em { color:#727b7e; font-style:normal; } .go-proof-copy { color:var(--go-muted); font-size:14px; line-height:1.7; max-width:350px; } .go-proof-stats { border-top:1px solid var(--go-line2); margin-top:48px; display:grid; grid-template-columns:repeat(3,1fr); } .go-proof-stat { padding-top:17px; border-right:1px solid var(--go-line); } .go-proof-stat:not(:first-child) { padding-left:20px; } .go-proof-stat b { font:500 22px "DM Mono",monospace; color:#dfe2df; } .go-proof-stat span { display:block; color:var(--go-dim); font:9px "DM Mono",monospace; margin-top:8px; text-transform:uppercase; }
        .go-approval { border:1px solid var(--go-line2); background:var(--go-panel); padding:25px; } .go-approval-head { display:flex; justify-content:space-between; border-bottom:1px solid var(--go-line); padding-bottom:18px; color:var(--go-dim); font:10px "DM Mono",monospace; } .go-approval-body { padding:25px 0 20px; } .go-approval-body h3 { font-size:15px; font-weight:600; } .go-approval-body p { color:var(--go-muted); font-size:12px; line-height:1.6; margin-top:9px; } .go-approval-row { display:flex; justify-content:space-between; color:#bbc0be; font:11px "DM Mono",monospace; padding:10px 0; border-top:1px solid var(--go-line); } .go-approval .go-button { width:100%; }
        .go-cta { padding:110px 0 125px; display:flex; align-items:end; justify-content:space-between; gap:30px; } .go-cta h2 { font-size:58px; line-height:1; letter-spacing:-.06em; margin-top:18px; } .go-cta h2 span { color:#737b7e; } .go-cta-copy { color:var(--go-muted); font-size:13px; line-height:1.7; max-width:260px; margin-bottom:2px; } .go-footer { height:100px; display:flex; justify-content:space-between; align-items:center; border-top:1px solid var(--go-line); color:var(--go-dim); font:10px "DM Mono",monospace; } .go-footer nav { display:flex; gap:25px; }
        .go-toast { position:fixed; bottom:25px; right:25px; border:1px solid var(--go-line2); background:#202429; color:var(--go-ink); padding:13px 16px; font:11px "DM Mono",monospace; z-index:5; animation:go-in .3s ease-out; } @keyframes go-in { from { opacity:0; transform:translateY(7px); } to { opacity:1; transform:translateY(0); } } .go-reveal { animation:go-reveal .7s ease-out both; } @keyframes go-reveal { from { opacity:0; transform:translateY(14px); } to { opacity:1; transform:translateY(0); } }
        .go-page { background:#0d1a2b; color:#eee5d2; } .go-page .go-console,.go-page .go-approval { background:#12233a; box-shadow:0 22px 60px rgba(2,11,24,.28); } .go-page .go-button,.go-page .go-toast { background:#1b3553; } .go-page .go-button:hover { background:#244364; border-color:#c2a875; } .go-page .go-row { border-top-color:#203650; } .go-page .go-row:hover,.go-page .go-row.active,.go-page .go-feature-tab:hover,.go-page .go-feature-tab.active { background:#19324f; } .go-page .go-cell strong,.go-page .go-amount { color:#eee5d2; } .go-page .go-pill.go-allowed { color:#d0c29e; } .go-page .go-pill.go-allowed i { background:#c2a875; } .go-page .go-pill.go-blocked { color:#d4b892; } .go-page .go-pill.go-blocked i { background:#b78f61; } .go-page .go-pill.go-escalated { color:#e0c58e; } .go-page .go-pill.go-escalated i { background:#c7a96c; } .go-page .go-approval-row { color:#d1c7b3; }
        @media (max-width:800px) { .go-wrap { padding:0 19px; } .go-navlinks { display:none; } .go-hero,.go-section-grid,.go-proof { grid-template-columns:1fr; gap:42px; } .go-hero { padding:80px 0; } .go-console { overflow:auto; } .go-table-head,.go-row { min-width:620px; } .go-section { padding:88px 0; } .go-flow { grid-template-columns:1fr; gap:22px; } .go-flow-arrow { display:none; } .go-feature { grid-template-columns:1fr; } .go-feature-nav { border-right:0; border-bottom:1px solid var(--go-line); } .go-feature-detail { min-height:230px; } .go-proof h2 { font-size:40px; } .go-cta { display:block; padding:88px 0; } .go-cta h2 { font-size:45px; margin-bottom:30px; } }
      `}</style>
      <div className="go-wrap">
        <nav className="go-nav">
          <a href="#top" className="go-logo"><i />ARCANUM</a>
          <div className="go-navlinks"><a href="#govern">Governance</a><a href="#ledger">Ledger</a><a href="#proof">Operators</a><button className="go-button" onClick={() => action("Access request queued")}>Request access <Arrow /></button></div>
        </nav>
        <section className="go-hero" id="top">
          <Reveal><div className="go-kicker">Governance layer / Arc mainnet</div><h1>Autonomy with a <span>boundary.</span></h1><p className="go-lead">ARCANUM gives every AI-agent wallet a policy, a verdict, and a human in the loop when the dollar needs one.</p><div className="go-hero-actions"><button className="go-button" onClick={() => action("Demo request queued")}>See the operating layer <Arrow /></button><a className="go-quiet-link" href="#ledger">Watch the ledger ↓</a></div></Reveal>
          <Reveal className="go-console" id="ledger"><div className="go-console-head"><span>ARC / OPERATIONS CONSOLE</span><span className="go-live"><i />LIVE · 42ms</span></div><div className="go-console-meta"><div className="go-stat"><b>$2.4M</b><span>governed</span></div><div className="go-stat"><b>18,492</b><span>decisions</span></div><div className="go-stat"><b>0.00%</b><span>unreviewed</span></div></div><div className="go-table-head"><span>TIME</span><span>AGENT / VENDOR</span><span>WALLET</span><span>AMOUNT</span><span>VERDICT</span></div>{transactions.map((tx, index) => <div key={tx.time} className={`go-row ${active === index ? "active" : ""}`} onMouseEnter={() => setActive(index)}><span className="go-cell go-mono" style={{ color:"var(--go-dim)", fontSize:10 }}>{tx.time}</span><span className="go-cell"><strong>{tx.agent}</strong><small>{tx.vendor}</small></span><span className="go-cell go-mono" style={{ color:"var(--go-dim)", fontSize:10 }}>{tx.address}</span><span className="go-amount">${tx.amount}</span><span className="go-cell"><VerdictPill verdict={tx.verdict} /><small>{tx.reason}</small></span></div>)}</Reveal>
        </section>
        <section className="go-section" id="govern"><div className="go-section-grid"><Reveal><div className="go-eyebrow">01 / The policy path</div><h2>Every dollar gets a second opinion.</h2><p className="go-section-intro">A deterministic check runs before settlement. No committee. No guesswork. Just the rules your finance team wrote.</p></Reveal><Reveal><div className="go-flow"><div className="go-flow-step"><div className="go-flow-num">01 — CHECK</div><b>Read the intent</b><p>Agent, vendor, amount and wallet arrive as one signed request.</p></div><div className="go-flow-arrow">→</div><div className="go-flow-step"><div className="go-flow-num">02 — DECIDE</div><b>Match the policy</b><p><span className="go-mono">$500/tx · $5,000/day</span><br />Allowlist and caps evaluate in 42ms.</p></div><div className="go-flow-arrow">→</div><div className="go-flow-step"><div className="go-flow-num">03 — ACT</div><b>Allow, block, escalate</b><p>Settle the clean spend. Stop the exception. Ask a human.</p></div></div></Reveal></div></section>
        <section className="go-section"><Reveal><div className="go-eyebrow">02 / Controls that hold</div><div className="go-feature" style={{ marginTop:34 }}><div className="go-feature-nav"><button className={`go-feature-tab ${feature === "policy" ? "active" : ""}`} onClick={() => setFeature("policy")}><b>Spending policies</b><span>CAPS · ALLOWLISTS · WINDOWS</span></button><button className={`go-feature-tab ${feature === "ledger" ? "active" : ""}`} onClick={() => setFeature("ledger")}><b>Immutable audit ledger</b><span>INTENT · VERDICT · SETTLEMENT</span></button><button className={`go-feature-tab ${feature === "approval" ? "active" : ""}`} onClick={() => setFeature("approval")}><b>Human escalation</b><span>ROUTING · APPROVAL · OVERRIDE</span></button></div><div className="go-feature-detail">{feature === "policy" && <><div><h3>Write the line before the agent crosses it.</h3><p>Apply per-transaction and daily caps by wallet, vendor, or agent. Policies live on Arc and execute before funds move.</p></div><code>if amount &gt; 500 → block</code></>}{feature === "ledger" && <><div><h3>Know what happened. Prove why.</h3><p>Every request carries its policy evaluation and settlement hash. Export an operator-readable record or inspect the raw event.</p></div><code>event: verdict / 0x3f…9a2c</code></>}{feature === "approval" && <><div><h3>Keep a human close to the edge cases.</h3><p>Route unusual spends to the right approver with context attached. Approve once, revoke any time.</p></div><code>queue: finance-ops / pending</code></>}</div></div></Reveal></section>
        <section className="go-section" id="proof"><div className="go-proof"><Reveal><div className="go-eyebrow">03 / Operator proof</div><h2>Trust is an <em>answer</em> to every “why”.</h2><div className="go-proof-stats"><div className="go-proof-stat"><b>42ms</b><span>policy checks</span></div><div className="go-proof-stat"><b>100%</b><span>ledger coverage</span></div><div className="go-proof-stat"><b>USDC</b><span>native settlement</span></div></div></Reveal><Reveal className="go-approval"><div className="go-approval-head"><span>REVIEW QUEUE / 01</span><span className="go-escalated">ESCALATED</span></div><div className="go-approval-body"><h3>procurement-bot wants $420.00</h3><p>Anthropic · 0x3f…9a2c<br />Reason: vendor requires human approval</p></div><div className="go-approval-row"><span>daily spend</span><span>$1,840 / $5,000</span></div><button className="go-button" onClick={() => { setApproved(!approved); action(approved ? "Approval revoked" : "Transaction approved"); }}>{approved ? "Revoke approval" : "Approve transaction"} <Arrow /></button></Reveal></div></section>
        <section className="go-cta"><div><div className="go-eyebrow">Put a boundary around autonomy</div><h2>Let agents work.<br /><span>Keep your hand on the switch.</span></h2></div><div className="go-cta-copy">The operating layer for agentic finance on Arc.<br /><button className="go-button" style={{ marginTop:22 }} onClick={() => action("Access request queued")}>Request early access <Arrow /></button></div></section>
        <footer className="go-footer"><span>© 2025 ARCANUM / thearcanum.in</span><nav><a href="#govern">Docs</a><a href="#proof">Status</a><a href="#top">Contact</a></nav></footer>
      </div>
      {toast && <div className="go-toast">{toast}</div>}
    </main>
  );
}