import React, { useEffect, useState } from "react";
import "./VitrineNoir.css";
import { ArrowUpRight, Check, ChevronRight, CircleAlert, Fingerprint, LockKeyhole, Menu, Shield, Sparkles, X } from "lucide-react";

type Verdict="ALLOWED"|"BLOCKED"|"ESCALATE";
const ledger:{time:string;agent:string;vendor:string;amount:string;verdict:Verdict;reason:string}[]=[
  {time:"14:42:08.311",agent:"procurement-bot",vendor:"AWS",amount:"$184.20",verdict:"ALLOWED",reason:"vendor allowlist / infra"},
  {time:"14:42:09.047",agent:"procurement-bot",vendor:"OpenAI",amount:"$620.00",verdict:"BLOCKED",reason:"daily cap exceeded"},
  {time:"14:42:11.803",agent:"treasury-bot",vendor:"Anthropic",amount:"$1,200.00",verdict:"ESCALATE",reason:"new vendor / human review"},
  {time:"14:42:14.190",agent:"ops-agent",vendor:"AWS",amount:"$48.60",verdict:"ALLOWED",reason:"policy AP-042 matched"},
];
function Kicker({children}:{children:React.ReactNode}){return <div className="mb-5 flex items-center gap-3 vn-mono text-[10px] uppercase tracking-[.22em] text-[#b9aa8c]"><span className="h-px w-8 bg-[#c4a77a]"/>{children}</div>}
function Status({v}:{v:Verdict}){let c=v==="ALLOWED"?"text-[#78c7a4] border-[#78c7a4]/30 bg-[#78c7a4]/[.08]":v==="BLOCKED"?"text-[#d77668] border-[#d77668]/30 bg-[#d77668]/[.08]":"text-[#d8c18e] border-[#d8c18e]/30 bg-[#d8c18e]/[.08]"; return <span className={`vn-mono inline-flex items-center gap-1.5 border px-2 py-1 text-[9px] tracking-[.12em] ${c}`}>{v==="ALLOWED"?<Check size={11}/>:v==="BLOCKED"?<X size={11}/>:<CircleAlert size={11}/>} {v}</span>}
function Count({to,suffix=""}:{to:number;suffix?:string}){const [n,setN]=useState(0);useEffect(()=>{let s=performance.now();let f=(t:number)=>{const p=Math.min((t-s)/1200,1);setN(Math.round(to*(1-Math.pow(1-p,3))));if(p<1)requestAnimationFrame(f)};requestAnimationFrame(f)},[to]);return <>{n.toLocaleString()}{suffix}</>}

export function VitrineNoir(){
 const [menu,setMenu]=useState(false); const [active,setActive]=useState(1); const [approved,setApproved]=useState(false);
 useEffect(()=>{const t=setInterval(()=>setActive(a=>(a+1)%ledger.length),2600);return()=>clearInterval(t)},[]);
 return <main className="vn-root min-h-[100dvh] overflow-hidden">
  <div className="vn-light pointer-events-none fixed -left-28 top-[18%] z-0 h-80 w-80 rounded-full bg-[#2a826c]/20 blur-[100px]"/><div className="vn-light pointer-events-none fixed right-[-8%] top-[-12%] z-0 h-[34rem] w-[34rem] rounded-full bg-[#bd9e62]/[.13] blur-[120px]" style={{animationDelay:"-4s"}}/>
  <nav className="vn-enter relative z-20 mx-auto flex max-w-[1240px] items-center justify-between border-b border-white/[.12] px-6 py-6 lg:px-10" style={{"--i":0} as React.CSSProperties}>
   <a href="#top" className="vn-display text-[21px] font-bold tracking-[.17em]">ARCANUM<span className="text-[#c4a77a]">·</span></a>
   <div className={`${menu?"flex":"hidden"} absolute left-0 top-full w-full flex-col gap-5 border-b border-white/10 bg-[#09201c]/95 p-6 backdrop-blur-xl md:static md:flex md:w-auto md:flex-row md:border-0 md:bg-transparent md:p-0`}><a href="#ledger" onClick={()=>setMenu(false)} className="text-xs uppercase tracking-[.15em] text-[#c0c9c1] hover:text-[#c4a77a]">The ledger</a><a href="#policies" onClick={()=>setMenu(false)} className="text-xs uppercase tracking-[.15em] text-[#c0c9c1] hover:text-[#c4a77a]">Policies</a><a href="#proof" onClick={()=>setMenu(false)} className="text-xs uppercase tracking-[.15em] text-[#c0c9c1] hover:text-[#c4a77a]">Audit proof</a></div>
   <div className="flex items-center gap-5"><a href="#contact" className="vn-press hidden border border-[#c4a77a]/50 px-4 py-2.5 text-[10px] font-semibold uppercase tracking-[.14em] text-[#d8c18e] md:block">Request access <ArrowUpRight className="ml-2 inline" size={13}/></a><button onClick={()=>setMenu(!menu)} className="md:hidden" aria-label="menu">{menu?<X size={20}/>:<Menu size={20}/>}</button></div>
  </nav>
  <section id="top" className="relative z-10 mx-auto grid max-w-[1240px] gap-16 px-6 pb-28 pt-20 lg:grid-cols-[.94fr_1.06fr] lg:items-center lg:px-10 lg:pb-36 lg:pt-28">
   <div className="vn-enter" style={{"--i":1} as React.CSSProperties}><Kicker>Non-custodial governance / Arc mainnet</Kicker><h1 className="vn-display max-w-[650px] text-[clamp(3.5rem,7vw,7.5rem)] font-light leading-[.88] tracking-[-.07em]">Money,<br/><em className="font-bold not-italic text-[#d8c18e]">under glass.</em></h1><p className="mt-9 max-w-[490px] text-[17px] leading-8 text-[#adbbb2]">The control layer for AI-agent USDC wallets. Every spend meets your policy before it leaves the wallet.</p><div className="mt-9 flex flex-wrap items-center gap-6"><a href="#ledger" className="vn-press bg-[#c4a77a] px-6 py-4 text-xs font-bold uppercase tracking-[.12em] text-[#13231e] shadow-[0_12px_30px_rgba(196,167,122,.18)]">Open the vitrine <ArrowUpRight className="ml-4 inline" size={15}/></a><span className="vn-mono text-[10px] leading-5 text-[#87998f]">42ms median policy check<br/>UTC / policy AP-042 / live</span></div></div>
   <div className="vn-enter relative" style={{"--i":2} as React.CSSProperties}><div className="absolute -inset-5 rounded-[50%] border border-[#c4a77a]/10"/><div className="vn-glass vn-sweep relative p-5 sm:p-7"><div className="flex items-center justify-between border-b border-white/[.14] pb-5"><span className="vn-mono text-[10px] tracking-[.12em] text-[#9fada4]">WALLET / 0x3f…9a2c</span><span className="flex items-center gap-2 text-[10px] text-[#78c7a4]"><i className="h-1.5 w-1.5 rounded-full bg-[#78c7a4]"/>ENFORCED</span></div><div className="py-9"><div className="vn-mono text-[9px] uppercase tracking-[.15em] text-[#82978d]">Governed balance</div><div className="vn-display mt-2 text-5xl font-bold tracking-[-.05em] sm:text-6xl">$48,230<span className="text-3xl font-light text-[#c4a77a]">.40</span></div></div><div className="grid grid-cols-2 border-y border-white/[.14]"><div className="p-4"><span className="vn-mono text-[9px] text-[#82978d]">DAILY CAP</span><strong className="mt-2 block text-lg font-medium">$5,000</strong></div><div className="border-l border-white/[.14] p-4"><span className="vn-mono text-[9px] text-[#82978d]">ALLOWLIST</span><strong className="mt-2 block text-lg font-medium">12 vendors</strong></div></div><div className="mt-5 flex items-center justify-between text-[10px] text-[#82978d]"><span className="vn-mono">POLICY / AP-042</span><span className="flex items-center gap-1.5"><Shield size={13} className="text-[#c4a77a]"/> Arc verified</span></div></div></div>
  </section>
  <section className="relative z-10 border-y border-white/[.1] bg-[#0a211c]/70 py-24 lg:py-32"><div className="mx-auto max-w-[1240px] px-6 lg:px-10"><Kicker>The transaction path</Kicker><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><h2 className="vn-display max-w-[650px] text-5xl font-light leading-[.95] tracking-[-.05em] lg:text-7xl">A dollar gets<br/><strong>three verdicts.</strong></h2><p className="max-w-[285px] text-sm leading-6 text-[#9eafa5]">No blind spots. The same hard perimeter for every instruction, every vendor, every agent.</p></div><div className="mt-16 grid border-t border-white/[.16] md:grid-cols-3">{[["01","CHECK","Read instruction, vendor, amount and context.","42ms median"],["02","DECIDE","Sign only when the policy perimeter holds.","ALLOW / BLOCK"],["03","ESCALATE","Hold ambiguous value for a human operator.","HUMAN IN THE LOOP"]].map((x,i)=><div className="border-b border-white/[.13] py-8 md:border-b-0 md:border-r md:px-8 md:first:pl-0" key={x[0]}><span className="vn-mono text-xs text-[#c4a77a]">{x[0]}</span><h3 className="vn-display mt-6 text-2xl font-bold">{x[1]}</h3><p className="mt-4 max-w-[260px] text-sm leading-6 text-[#9eafa5]">{x[2]}</p><span className="vn-mono mt-8 block text-[10px] tracking-[.1em] text-[#78c7a4]">{x[3]}</span></div>)}</div></div></section>
  <section id="ledger" className="relative z-10 mx-auto grid max-w-[1240px] gap-14 px-6 py-24 lg:grid-cols-[.68fr_1.32fr] lg:px-10 lg:py-32"><div><Kicker>Signature / governed ledger</Kicker><h2 className="vn-display text-5xl font-light leading-[.95] tracking-[-.05em] lg:text-6xl">The verdict<br/><strong className="text-[#d8c18e]">is the record.</strong></h2><p className="mt-7 max-w-[310px] text-sm leading-6 text-[#9eafa5]">Policy enforcement at the edge, with an audit trail your finance team can read without a decoder ring.</p><div className="vn-glass mt-10 p-5"><div className="vn-mono text-[9px] text-[#82978d]">GOVERNED THIS MONTH</div><div className="vn-display mt-2 text-3xl font-bold text-[#e7e2d6]">$<Count to={2400000}/></div><div className="mt-1 text-xs text-[#82978d]">USDC · 1,284 decisions signed</div></div></div><div className="vn-glass overflow-hidden"><div className="flex items-center justify-between border-b border-white/[.14] p-5"><div><span className="vn-mono text-[10px] uppercase tracking-[.13em] text-[#c4a77a]">Live stream</span><div className="mt-1 text-sm text-[#c3cec7]">Policy decisions / UTC</div></div><Fingerprint size={21} className="text-[#c4a77a]"/></div>{ledger.map((r,i)=><div key={r.time} className={`vn-stream flex flex-col gap-3 border-b border-white/[.1] p-5 sm:grid sm:grid-cols-[1.5fr_1fr_auto] sm:items-center ${active===i?"bg-white/[.055]":""}`} style={{animationDelay:`${i*.25}s`}}><div><div className="flex items-center gap-3 text-sm"><span className="text-[#e7e2d6]">{r.vendor}</span><span className="vn-mono text-[9px] text-[#84968d]">{r.agent}</span></div><div className="vn-mono mt-1 text-[9px] text-[#71877d]">{r.time} · {r.reason}</div></div><div className="vn-mono text-sm tabular-nums text-[#c9d2cb] sm:text-right">{r.amount}</div><div className="sm:justify-self-end"><Status v={r.verdict}/></div></div>)}<div className="flex items-center justify-between p-5"><span className="vn-mono text-[9px] text-[#71877d]">SIGNED BY ARCANUM / ARC</span><a href="#proof" className="text-xs text-[#c4a77a]">View full audit <ChevronRight size={14} className="ml-1 inline"/></a></div></div></section>
  <section id="policies" className="relative z-10 border-y border-white/[.1] bg-[#0a211c]/55 py-24 lg:py-32"><div className="mx-auto max-w-[1240px] px-6 lg:px-10"><Kicker>Policy surface / AP-042</Kicker><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><h2 className="vn-display text-5xl font-light leading-[.94] tracking-[-.05em] lg:text-6xl">The perimeter<br/><strong>stays precise.</strong></h2><p className="mt-7 max-w-[340px] text-sm leading-6 text-[#9eafa5]">Write guardrails once. Arcanum evaluates them on every call, without taking custody of a cent.</p></div><div className="grid gap-px bg-white/[.14] sm:grid-cols-2"><div className="vn-glass p-7"><LockKeyhole size={20} className="text-[#c4a77a]"/><h3 className="vn-display mt-8 text-2xl">Hard caps</h3><p className="mt-3 text-sm leading-6 text-[#9eafa5]">$500 per transaction · $5,000 per day. Velocity rules prevent burst spend.</p></div><div className="vn-glass p-7"><Check size={20} className="text-[#78c7a4]"/><h3 className="vn-display mt-8 text-2xl">Vendor allowlists</h3><p className="mt-3 text-sm leading-6 text-[#9eafa5]">12 approved vendors. New destinations route to review, never silently pass.</p></div><div className="vn-glass p-7 sm:col-span-2"><Sparkles size={20} className="text-[#c4a77a]"/><h3 className="vn-display mt-8 text-2xl">Anomaly context, not just a number</h3><p className="mt-3 max-w-[530px] text-sm leading-6 text-[#9eafa5]">Agent, vendor, time, velocity and instruction intent travel with every decision. An operator sees why before they approve.</p></div></div></div></div></section>
  <section id="proof" className="relative z-10 mx-auto max-w-[1240px] px-6 py-24 lg:px-10 lg:py-32"><div className="vn-glass p-8 sm:p-12 lg:p-16"><div className="grid gap-14 lg:grid-cols-[1fr_1.2fr] lg:items-end"><div><Kicker>Audit proof / always on</Kicker><h2 className="vn-display text-5xl font-light leading-[.95] tracking-[-.05em]">Trust is<br/><strong>observable.</strong></h2><p className="mt-7 max-w-[330px] text-sm leading-6 text-[#9eafa5]">Every allowed, blocked and escalated event is signed, timestamped and queryable. Nothing gets lost in a dashboard.</p></div><div className="grid grid-cols-2 gap-8 border-t border-white/[.14] pt-8 sm:grid-cols-3"><div><div className="vn-display text-4xl font-bold">100%</div><div className="vn-mono mt-2 text-[9px] text-[#82978d]">DECISIONS LOGGED</div></div><div><div className="vn-display text-4xl font-bold">42ms</div><div className="vn-mono mt-2 text-[9px] text-[#82978d]">MEDIAN CHECK</div></div><div><div className="vn-display text-4xl font-bold">0</div><div className="vn-mono mt-2 text-[9px] text-[#82978d]">CUSTODY HELD</div></div></div></div></div></section>
  <section id="contact" className="relative z-10 px-6 pb-28 pt-4 text-center lg:pb-36"><Kicker>Private access / operators only</Kicker><h2 className="vn-display mx-auto max-w-[850px] text-6xl font-light leading-[.9] tracking-[-.06em] sm:text-8xl">Put your agents<br/><strong>under glass.</strong></h2><p className="mx-auto mt-8 max-w-[410px] text-sm leading-6 text-[#9eafa5]">Bring your policy perimeter to Arc. We will show you the exact decision path for your first wallet.</p><button onClick={()=>setApproved(true)} className="vn-press mt-9 bg-[#c4a77a] px-7 py-4 text-xs font-bold uppercase tracking-[.13em] text-[#13231e]">{approved?"Request received":"Request private access"} <ArrowUpRight className="ml-4 inline" size={15}/></button>{approved&&<div className="vn-mono mt-4 text-[10px] text-[#78c7a4]">ACK / 14:42:12 UTC · WE’LL BE IN TOUCH</div>}</section>
  <footer className="relative z-10 flex flex-col justify-between gap-4 border-t border-white/[.12] px-6 py-7 text-[10px] text-[#71877d] sm:flex-row lg:px-10"><span className="vn-display text-base tracking-[.16em] text-[#c3cec7]">ARCANUM<span className="text-[#c4a77a]">·</span></span><span className="vn-mono">NON-CUSTODIAL GOVERNANCE FOR ARC / 2024</span><span>Built for the people who sign.</span></footer>
 </main>
}