from __future__ import annotations

import json
import pprint
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ABI_DIR = ROOT / "contracts" / "abis"
OUTPUT = Path(__file__).resolve().parents[1] / "src" / "arcanum_sdk" / "abi.py"

SELECTIONS = {
    "GUARDED_WALLET_ABI": (
        "GuardedWallet.json",
        {
            ("function", name)
            for name in (
                "agentSigners",
                "dailySpent",
                "escalationManager",
                "executeUSDC",
                "frozen",
                "monthlySpent",
                "policy",
                "policyEngine",
                "vendorRegistry",
            )
        }
        | {("event", "TransferEscalated")}
        | {("error", "*")},
    ),
    "POLICY_ENGINE_ABI": ("PolicyEngine.json", {("function", "evaluate")}),
    "VENDOR_REGISTRY_ABI": ("VendorRegistry.json", {("function", "getVendorFor")}),
    "ESCALATION_MANAGER_ABI": (
        "EscalationManager.json",
        {("function", "getEscalation"), ("function", "statusOf")},
    ),
}

ERC20_ABI = [
    {
        "type": "function",
        "name": "balanceOf",
        "inputs": [{"name": "account", "type": "address"}],
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "view",
    }
]


def selected(entry: dict[str, object], wanted: set[tuple[str, str]]) -> bool:
    entry_type = str(entry.get("type", ""))
    name = str(entry.get("name", ""))
    return (entry_type, name) in wanted or (entry_type, "*") in wanted


def main() -> None:
    sections: list[str] = [
        "# Generated by scripts/gen_abi.py from packages/contracts/abis. Do not edit.",
        "",
    ]
    for constant, (filename, wanted) in SELECTIONS.items():
        source = json.loads((ABI_DIR / filename).read_text())
        fragment = [entry for entry in source if selected(entry, wanted)]
        sections.extend((f"{constant} = {pprint.pformat(fragment, width=100)}", ""))
    sections.append(f"ERC20_ABI = {pprint.pformat(ERC20_ABI, width=100)}")
    OUTPUT.write_text("\n".join(sections) + "\n")


if __name__ == "__main__":
    main()