import React, { useEffect, useState } from "react";

type Verdict = "ALLOWED" | "BLOCKED" | "ESCALATED";

const rows: Array<{ time: string; agent: string; vendor: string; amount: string; wallet: string; verdict: Verdict; detail: string }> = [
  { time: "09:41:08", agent: "procurement-bot", vendor: "AWS", amount: "$184.00", wallet: "0x3f…9a2c", verdict: "ALLOWED", detail: "vendor allowlist · under cap" },
  { time: "09:41:14", agent: "research-bot", vendor: "OpenAI", amount: "$68.40", wallet: "0x8c…41ef", verdict: "ALLOWED", detail: "vendor allowlist · under cap" },
  { time: "09:41:22", agent: "procurement-bot", vendor: "Anthropic", amount: "$920.00", wallet: "0x3f…9a2c", verdict: "BLOCKED", detail: "over $500 / transaction cap" },
  { time: "09:41:27", agent: "ops-agent", vendor: "AWS", amount: "$1,200.00", wallet: "0xb1…77d0", verdict: "ESCALATED", detail: "human approval required" },
];

function Verdict({ value }: { value: Verdict }) {
  const styles = {
    ALLOWED: "border-[#8ea88d] text-[#b9d6b7]",
    BLOCKED: "border-[#d39aa4] text-[#f0b5bf]",
    ESCALATED: "border-[#e3c487] text-[#f2d39a]",
  }[value];
  return <span className={`inline-flex items-center gap-2 border px-2 py-1 font-mono text-[9px] tracking-[.18em] ${styles}`}><i className="h-1.5 w-1.5 rounded-full bg-current" />{value}</span>;
}

function Label({ children }: { children: React.ReactNode }) {
  return <p className="mb-4 font-mono text-[10px] uppercase tracking-[.24em] text-[#b9abc4]">{children}</p>;
}

export function AubergineVelvet() {
  const [active, setActive] = useState(2);
  const [briefing, setBriefing] = useState(false);
  const [menu, setMenu] = useState(false);
  useEffect(() => {
    const timer = window.setInterval(() => setActive((v) => (v + 1) % rows.length), 3200);
    return () => window.clearInterval(timer);
  }, []);
  const go = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
  return (
    <main className="min-h-[100dvh] overflow-hidden bg-[#211427] text-[#eee6ed]" style={{ fontFamily: "'DM Sans',sans-serif" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=DM+Mono:wght@400;500&family=Instrument+Serif:ital@0;1&display=swap');
        html{scroll-behavior:smooth}.serif{font-family:'Instrument Serif',Georgia,serif}.mono{font-family:'DM Mono',monospace;font-variant-numeric:tabular-nums}
        .velvet{background:#211427}.plum{background:#2d1b32}.plum2{background:#39233e}.line{border-color:#604b67}
        .reveal{animation:rise .9s both cubic-bezier(.16,.8,.24,1)}.d1{animation-delay:.12s}.d2{animation-delay:.24s}.d3{animation-delay:.36s}
        @keyframes rise{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:translateY(0)}} @keyframes pulse{0%,100%{opacity:.55;transform:scale(1)}50%{opacity:1;transform:scale(1.2)}}
        .pulse{animation:pulse 2s ease-in-out infinite}.grain:after{content:'';pointer-events:none;position:fixed;inset:0;opacity:.035;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='160' height='160'%3E%3Cfilter id='n'%3E%3CfeTurbulence baseFrequency='.8' numOctaves='3'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.5'/%3E%3C/svg%3E");z-index:30}
        button,a{transition:transform .2s ease,opacity .2s ease,color .2s ease,background-color .2s ease,border-color .2s ease}button:active,a:active{transform:translateY(1px)}
      `}</style>
      <div className="grain">
        <header className="relative mx-auto flex max-w-[1240px] items-center justify-between border-b line px-6 py-5 lg:px-10">
          <button onClick={() => go("top")} className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center border border-[#e4c98e] text-xs text-[#e4c98e]">A</span><b className="text-[13px] tracking-[.3em]">ARCANUM</b></button>
          <nav className="hidden items-center gap-9 md:flex"><button onClick={() => go("method")} className="mono text-[10px] uppercase tracking-[.16em] text-[#b9abc4] hover:text-[#e4c98e]">The method</button><button onClick={() => go("ledger")} className="mono text-[10px] uppercase tracking-[.16em] text-[#b9abc4] hover:text-[#e4c98e]">Live ledger</button><button onClick={() => go("controls")} className="mono text-[10px] uppercase tracking-[.16em] text-[#b9abc4] hover:text-[#e4c98e]">Controls</button></nav>
          <button onClick={() => setBriefing(true)} className="border border-[#8b718f] px-4 py-2 font-mono text-[10px] uppercase tracking-[.14em] hover:border-[#e4c98e] hover:text-[#e4c98e]">Request a briefing</button>
          {briefing && <div className="absolute right-5 top-[68px] z-10 w-72 border line bg-[#39233e] p-5"><p className="serif text-2xl">A private conversation.</p><p className="mt-2 text-xs leading-5 text-[#c7b7c6]">Bring one agent and one policy. We will trace the dollar together.</p><button onClick={() => setBriefing(false)} className="mt-5 w-full border border-[#8b718f] py-2 font-mono text-[10px] uppercase tracking-widest hover:bg-[#e4c98e] hover:text-[#211427]">Close</button></div>}
        </header>

        <section id="top" className="mx-auto grid max-w-[1240px] gap-14 px-6 pb-28 pt-24 lg:grid-cols-[1fr_.9fr] lg:px-10 lg:pb-36 lg:pt-32">
          <div className="reveal"><Label>Governance layer · Arc network</Label><h1 className="serif max-w-[720px] text-[clamp(4rem,8vw,8.3rem)] leading-[.84] tracking-[-.055em]">The wallet<br /><em className="text-[#e4c98e]">answers to you.</em></h1><p className="mt-9 max-w-[510px] text-[17px] leading-7 text-[#cbbdca]">Autonomous agents can move money quickly. ARCANUM makes sure they move it only where your policy says they can.</p><div className="mt-10 flex flex-wrap items-center gap-5"><button onClick={() => go("ledger")} className="bg-[#e4c98e] px-6 py-3.5 text-[12px] font-semibold tracking-[.06em] text-[#211427] hover:bg-[#f4dda8]">Watch a dollar move <span className="ml-5">↗</span></button><button onClick={() => go("method")} className="border-b border-[#e4c98e] pb-1 text-[12px] text-[#d8c9d6] hover:text-[#e4c98e]">Read the method</button></div><div className="mt-20 grid max-w-[580px] grid-cols-3 border-t line pt-5"><div><p className="mono text-[22px] text-[#f2d39a]">$2.4M</p><p className="mt-1 text-[10px] uppercase tracking-[.15em] text-[#b9abc4]">governed</p></div><div><p className="mono text-[22px] text-[#f2d39a]">42ms</p><p className="mt-1 text-[10px] uppercase tracking-[.15em] text-[#b9abc4]">policy checks</p></div><div><p className="mono text-[22px] text-[#f2d39a]">0</p><p className="mt-1 text-[10px] uppercase tracking-[.15em] text-[#b9abc4]">unreviewed exceptions</p></div></div></div>
          <div className="reveal d2 relative flex min-h-[490px] items-center justify-center"><div className="absolute right-0 top-0 h-[400px] w-[80%] border line bg-[#2d1b32]" /><div className="absolute left-0 top-16 h-[400px] w-[84%] border line bg-[#39233e]" /><div className="relative z-[1] w-[89%] border border-[#806881] bg-[#302037] p-7 shadow-[14px_18px_0_#19101e]"><div className="flex items-start justify-between border-b line pb-6"><div><p className="mono text-[9px] uppercase tracking-[.2em] text-[#b9abc4]">Policy instrument · 00042</p><p className="serif mt-2 text-3xl">Spending authority</p></div><span className="text-2xl text-[#e4c98e]">✦</span></div><p className="py-7 text-[11px] leading-5 text-[#c7b7c6]">A wallet that can act, but cannot improvise beyond the boundaries inscribed below.</p><div className="grid grid-cols-2 gap-y-6 border-y line py-5"><div><p className="mono text-[9px] uppercase tracking-wider text-[#b9abc4]">Agent</p><p className="mt-1 text-sm">procurement-bot</p></div><div><p className="mono text-[9px] uppercase tracking-wider text-[#b9abc4]">Network</p><p className="mt-1 text-sm">Arc / USDC</p></div><div><p className="mono text-[9px] uppercase tracking-wider text-[#b9abc4]">Per transaction</p><p className="mono mt-1 text-sm text-[#f2d39a]">$500.00</p></div><div><p className="mono text-[9px] uppercase tracking-wider text-[#b9abc4]">Per day</p><p className="mono mt-1 text-sm text-[#f2d39a]">$5,000.00</p></div></div><div className="mt-7 flex justify-between"><p className="serif text-xl italic text-[#d4bdd4]">R. Sato</p><p className="mono self-end text-[9px] text-[#e4c98e]">VALID / ACTIVE</p></div></div></div>
        </section>

        <section id="method" className="border-y line bg-[#2d1b32]"><div className="mx-auto max-w-[1240px] px-6 py-24 lg:px-10"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><Label>How a dollar gets governed</Label><h2 className="serif text-5xl leading-[.95] tracking-[-.035em]">No guesswork<br />between intent<br /><em className="text-[#e4c98e]">and settlement.</em></h2></div><div className="grid gap-px bg-[#604b67] md:grid-cols-3"><div className="bg-[#2d1b32] p-7"><span className="mono text-[#e4c98e]">01</span><h3 className="serif mt-16 text-3xl">Policy check</h3><p className="mt-4 text-sm leading-6 text-[#c7b7c6]">42ms to compare vendor, amount, wallet and daily context.</p></div><div className="bg-[#2d1b32] p-7"><span className="mono text-[#e4c98e]">02</span><h3 className="serif mt-16 text-3xl">Allow or block</h3><p className="mt-4 text-sm leading-6 text-[#c7b7c6]">The transaction receives a deterministic verdict before it touches the chain.</p></div><div className="bg-[#2d1b32] p-7"><span className="mono text-[#e4c98e]">03</span><h3 className="serif mt-16 text-3xl">Escalate</h3><p className="mt-4 text-sm leading-6 text-[#c7b7c6]">Route the edge case to a named human. Keep the agent moving, safely.</p></div></div></div></div></section>

        <section id="ledger" className="mx-auto max-w-[1240px] px-6 py-28 lg:px-10"><div className="flex flex-wrap items-end justify-between gap-6"><div><Label>Signature moment · live governed ledger</Label><h2 className="serif text-6xl tracking-[-.04em]">Every verdict,<br /><em className="text-[#e4c98e]">in the open.</em></h2></div><p className="max-w-[270px] text-sm leading-6 text-[#c7b7c6]">A quiet stream of decisions from the wallets your team governs.</p></div><div className="mt-14 overflow-x-auto border line bg-[#2d1b32]"><div className="min-w-[760px]"><div className="grid grid-cols-[110px_1.2fr_1fr_110px_125px_150px] border-b line px-5 py-4 font-mono text-[9px] uppercase tracking-[.15em] text-[#9f8ba4]"><span>Time</span><span>Agent</span><span>Vendor</span><span>Amount</span><span>Verdict</span><span>Rule</span></div>{rows.map((row, i) => <div key={row.time} className={`grid grid-cols-[110px_1.2fr_1fr_110px_125px_150px] items-center border-b line px-5 py-5 text-xs transition-all duration-500 ${active === i ? "bg-[#412747]" : ""}`}><span className="mono text-[#9f8ba4]">{row.time}</span><span className="mono">{row.agent}</span><span>{row.vendor}</span><span className="mono text-[#f2d39a]">{row.amount}</span><span><Verdict value={row.verdict} /></span><span className="text-[#b9abc4]">{row.detail}</span></div>)}</div></div><div className="mt-5 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[.14em] text-[#9f8ba4]"><span className="pulse h-2 w-2 rounded-full bg-[#e4c98e]" />Stream live · block and escalate animations repeat every 3.2s</div></section>

        <section id="controls" className="bg-[#39233e]"><div className="mx-auto grid max-w-[1240px] gap-14 px-6 py-28 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div><Label>Policy is the product</Label><h2 className="serif text-6xl leading-[.9]">The rails<br /><em className="text-[#e4c98e]">stay visible.</em></h2><p className="mt-7 max-w-[370px] text-sm leading-6 text-[#c7b7c6]">Write the boundaries once. Let agents execute inside them. See every exception as it happens.</p></div><div className="border line bg-[#2d1b32]"><div className="flex items-center justify-between border-b line px-6 py-5"><div><p className="mono text-[9px] uppercase tracking-[.2em] text-[#b9abc4]">Active policy</p><p className="mt-1 text-lg">procurement-bot / production</p></div><span className="mono text-[10px] text-[#b9d6b7]">● ON</span></div><div className="grid gap-0 md:grid-cols-2"><div className="border-b line p-6 md:border-r"><p className="mono text-[9px] uppercase tracking-widest text-[#b9abc4]">Transaction cap</p><p className="mono mt-8 text-4xl text-[#f2d39a]">$500</p><p className="mt-2 text-xs text-[#9f8ba4]">per transaction</p></div><div className="border-b line p-6"><p className="mono text-[9px] uppercase tracking-widest text-[#b9abc4]">Daily cap</p><p className="mono mt-8 text-4xl text-[#f2d39a]">$5,000</p><p className="mt-2 text-xs text-[#9f8ba4]">rolling 24 hours</p></div><div className="p-6 md:col-span-2"><p className="mono text-[9px] uppercase tracking-widest text-[#b9abc4]">Allowed vendors</p><div className="mt-5 flex flex-wrap gap-2">{["AWS","OpenAI","Anthropic"].map(v => <span key={v} className="border line px-3 py-2 text-sm">{v}<b className="ml-3 text-[#b9d6b7]">✓</b></span>)}</div></div></div></div></div></section>

        <section className="mx-auto max-w-[1240px] px-6 py-28 lg:px-10"><div className="border-y line py-14 text-center"><Label>Proof in the ledger</Label><p className="serif mx-auto max-w-[850px] text-4xl leading-tight md:text-6xl">“We gave our agents room to work without giving them room to surprise us.”</p><p className="mono mt-7 text-[10px] uppercase tracking-[.18em] text-[#b9abc4]">Mira Chen · VP Finance · Atlas Systems</p></div></section>
        <section className="bg-[#e4c98e] text-[#211427]"><div className="mx-auto flex max-w-[1240px] flex-wrap items-center justify-between gap-8 px-6 py-20 lg:px-10"><div><p className="mono mb-4 text-[10px] uppercase tracking-[.2em] opacity-70">Give your agents a wallet</p><h2 className="serif text-6xl leading-[.9]">Keep the<br /><em>final word.</em></h2></div><button onClick={() => setBriefing(true)} className="border border-[#211427] px-7 py-4 text-xs font-semibold uppercase tracking-[.1em] hover:bg-[#211427] hover:text-[#e4c98e]">Request a private briefing ↗</button></div></section>
        <footer className="mx-auto flex max-w-[1240px] flex-wrap justify-between gap-8 px-6 py-10 lg:px-10"><p className="text-[12px] tracking-[.25em]">ARCANUM</p><p className="mono text-[10px] text-[#9f8ba4]">NON-CUSTODIAL GOVERNANCE FOR AI WALLETS</p><button onClick={() => go("top")} className="mono text-[10px] uppercase tracking-widest text-[#b9abc4] hover:text-[#e4c98e]">Back to top ↑</button></footer>
      </div>
    </main>
  );
}