import React, { useEffect, useState } from "react";
import "./NordGlass.css";

const Icon = ({ children, size = 18 }: { children: React.ReactNode; size?: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{children}</svg>
);
const Arrow = () => <Icon><path d="M5 12h13M13 6l6 6-6 6"/></Icon>;
const Check = () => <Icon><path d="m5 12 4 4L19 6"/></Icon>;
const Count = ({ to, suffix = "" }: { to: number; suffix?: string }) => {
  const [n, setN] = useState(0);
  useEffect(() => { let start = 0; const step = () => { start += Math.max(1, to / 38); if (start >= to) setN(to); else { setN(Math.floor(start)); requestAnimationFrame(step); } }; const id = requestAnimationFrame(step); return () => cancelAnimationFrame(id); }, [to]);
  return <>{n.toLocaleString()}{suffix}</>;
};
const GlassTag = ({ children, tone = "light" }: { children: React.ReactNode; tone?: "light"|"dark" }) => <span className={`inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-[10px] uppercase tracking-[.16em] ${tone==="dark" ? "bg-white/10 text-[#d6edef]":"bg-white/55 text-[#32616a] border border-white/70"}`}>{children}</span>;

function LedgerStream() {
  const entries = [
    { label:"Hologram Systems", detail:"0x3f…9a2c · 14:08:22 UTC", amount:"$420.00", state:"ALLOWED", color:"text-[#b9e8d2]" },
    { label:"Cloudflare, Inc.", detail:"0x81…b71d · 14:08:19 UTC", amount:"$1,240.00", state:"ESCALATE", color:"text-[#dce8a7]" },
    { label:"New vendor · unknown", detail:"0x27…c019 · 14:08:16 UTC", amount:"$8,760.00", state:"BLOCKED", color:"text-[#f1b6a7]" },
  ];
  return <div className="glass-dark specular relative rounded-[26px] p-5 md:p-7">
    <div className="mb-6 flex items-center justify-between"><div><p className="mono text-[10px] uppercase tracking-[.18em] text-[#a8c9cc]">Governed ledger / live</p><p className="display mt-1 text-xl">The money trail, in real time.</p></div><span className="flex items-center gap-2 text-[10px] text-[#b9e8d2]"><i className="h-1.5 w-1.5 rounded-full bg-[#8bd4ad] shadow-[0_0_0_4px_rgba(139,212,173,.15)]"/>streaming</span></div>
    <div className="space-y-2.5">
      {entries.map((e, i) => <div key={e.label} style={{animation:`ledgerIn .6s cubic-bezier(.16,1,.3,1) both`,animationDelay:`${i * 650}ms`}} className={`relative flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[.065] px-3 py-3 ${i===2?"opacity-75":""}`}>
        <div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-white/[.09] ${e.color}`}>{i===0?<Check/>:i===1?<Icon><path d="M12 8v4l2 2"/><circle cx="12" cy="12" r="8"/></Icon>:<Icon><path d="M12 3 3 20h18L12 3Z"/><path d="M12 9v4M12 16h.01"/></Icon>}</div>
        <div className="min-w-0 flex-1"><p className="text-[12px] font-medium text-[#edf7f7]">{e.label}</p><p className="mono mt-1 truncate text-[9px] text-[#8eafb2]">{e.detail}</p></div>
        <div className="text-right"><p className="mono text-[12px] text-[#effafa]">{e.amount}</p><p className={`mono mt-1 text-[9px] tracking-[.12em] ${e.color}`}>{e.state}</p></div>
        {i===2 && <div className="crack"/>}
      </div>)}
    </div>
    <div className="mt-5 flex items-center justify-between border-t border-white/10 pt-4"><span className="mono text-[10px] text-[#8eafb2]">POLICY ARC-042 · v3.8</span><span className="text-[10px] text-[#aecacc]">42ms median check</span></div>
  </div>;
}

export function NordGlass() {
  return <main className="nordglass ng-world min-h-[100dvh]">
    <div className="grain"/>
    <nav className="relative z-10 mx-auto flex max-w-[1220px] items-center justify-between px-6 py-6 md:px-10">
      <a href="#top" className="display text-[19px] font-extrabold tracking-[-.07em] text-[#173f48]">ARCANUM<span className="ml-1 align-top text-[8px] font-semibold tracking-[.15em] text-[#39848a]">/ ARC</span></a>
      <div className="hidden items-center gap-9 text-[12px] font-medium text-[#39616a] md:flex"><a className="ng-link" href="#govern">Governance</a><a className="ng-link" href="#policy">Policies</a><a className="ng-link" href="#audit">Audit trail</a></div>
      <a href="#contact" className="ng-button glass rounded-full px-4 py-2.5 text-[11px] font-semibold text-[#245b64]">Request access <span className="ml-2">↗</span></a>
    </nav>
    <section id="top" className="relative z-10 mx-auto grid max-w-[1220px] items-center gap-14 px-6 pb-24 pt-12 md:grid-cols-[.95fr_1.05fr] md:px-10 md:pb-36 md:pt-20">
      <div className="reveal" style={{"--i":1} as React.CSSProperties}><GlassTag><span className="h-1.5 w-1.5 rounded-full bg-[#0b8585]"/> Built for Arc</GlassTag><h1 className="display mt-7 max-w-[640px] text-[clamp(3.5rem,7.6vw,7rem)] font-light leading-[.88] text-[#173f48]">Every dollar.<br/><span className="font-extrabold">Accountable.</span></h1><p className="mt-7 max-w-[470px] text-[16px] leading-7 text-[#496c73]">ARCanum is the non-custodial governance layer for AI-agent wallets. Set the rules. Let agents move. Keep the final say.</p><div className="mt-9 flex flex-wrap items-center gap-4"><a href="#contact" className="ng-button inline-flex items-center gap-3 rounded-full bg-[#087f83] px-5 py-3.5 text-[12px] font-semibold text-[#effafa] shadow-[0_10px_24px_rgba(8,127,131,.2)]">Govern an agent <Arrow/></a><span className="mono text-[10px] text-[#53747a]">No custody. No blind spots.</span></div><div className="mt-14 flex gap-8 border-t border-[#a8c8cc] pt-5"><div><p className="mono text-2xl text-[#173f48]"><Count to={42}/>ms</p><p className="mt-1 text-[10px] uppercase tracking-[.13em] text-[#628188]">median policy check</p></div><div><p className="mono text-2xl text-[#173f48]">$<Count to={24}/><span className="text-lg">M</span></p><p className="mt-1 text-[10px] uppercase tracking-[.13em] text-[#628188]">governed volume</p></div></div></div>
      <div className="reveal relative" style={{"--i":3} as React.CSSProperties}><div className="absolute -inset-8 rounded-[40px] bg-[#b9e8ea]/40 blur-3xl"/><LedgerStream/></div>
    </section>
    <section id="govern" className="relative z-10 mx-auto max-w-[1220px] px-6 py-20 md:px-10 md:py-28"><div className="mb-14 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mono text-[10px] uppercase tracking-[.18em] text-[#4a7c84]">01 / The control plane</p><h2 className="display mt-4 max-w-[550px] text-4xl font-light leading-[.95] text-[#173f48] md:text-6xl">How a dollar gets governed.</h2></div><p className="max-w-[300px] text-sm leading-6 text-[#55767c]">A policy check happens before the transaction reaches the chain. Every time. Automatically.</p></div><div className="grid gap-4 md:grid-cols-[1.15fr_.85fr_1fr]"><div className="glass specular rounded-[25px] p-7 md:translate-y-5"><span className="mono text-[11px] text-[#4f8087]">01 — INTENT</span><h3 className="display mt-10 text-3xl font-semibold">Agent requests<br/>to spend.</h3><p className="mt-12 text-sm leading-6 text-[#58777d]">The wallet signs nothing yet. ARCanum catches the intent at the edge.</p></div><div className="glass-dark rounded-[25px] p-7"><span className="mono text-[11px] text-[#b7d6d8]">02 — POLICY</span><h3 className="display mt-10 text-3xl font-semibold">Rules decide<br/>in 42ms.</h3><div className="mt-10 space-y-3 text-[11px] text-[#c5e0e1]"><p className="flex gap-2"><Check/> $500 per transaction</p><p className="flex gap-2"><Check/> Approved vendors only</p><p className="flex gap-2"><Check/> $5,000 daily velocity</p></div></div><div className="glass specular rounded-[25px] p-7 md:translate-y-10"><span className="mono text-[11px] text-[#4f8087]">03 — VERDICT</span><h3 className="display mt-10 text-3xl font-semibold">Allow, block,<br/>or ask a human.</h3><p className="mt-12 text-sm leading-6 text-[#58777d]">The decision and its reason become a permanent, exportable record.</p></div></div></section>
    <section id="policy" className="relative z-10 overflow-hidden bg-[#1b4b55] px-6 py-24 text-[#effafa] md:px-10 md:py-32"><div className="mx-auto grid max-w-[1220px] gap-16 md:grid-cols-[.72fr_1.28fr]"><div><p className="mono text-[10px] uppercase tracking-[.18em] text-[#9fcacd]">02 / Policy fabric</p><h2 className="display mt-5 text-5xl font-light leading-[.92] md:text-7xl">Your rules,<br/><span className="font-extrabold">machine-readable.</span></h2><p className="mt-7 max-w-[340px] text-sm leading-6 text-[#b8d4d6]">Precise enough for finance. Fast enough for an agent. Visible to everyone who should be looking.</p><a href="#contact" className="ng-link mt-10 inline-flex items-center gap-3 text-sm text-[#d1eeee]">See a policy in action <Arrow/></a></div><div className="grid gap-3 sm:grid-cols-2"><div className="glass-dark specular rounded-[24px] p-6"><p className="mono text-[10px] text-[#97c1c4]">CAPS / ARC-042</p><p className="display mt-12 text-4xl">$500</p><p className="mt-2 text-xs text-[#b8d4d6]">per transaction</p><div className="mt-6 h-px bg-white/15"/><p className="mono mt-4 text-[11px] text-[#d3e8e8]">$5,000 / day</p></div><div className="glass-dark specular rounded-[24px] p-6 sm:translate-y-8"><p className="mono text-[10px] text-[#97c1c4]">ALLOWLIST / 18</p><p className="display mt-12 text-4xl">18</p><p className="mt-2 text-xs text-[#b8d4d6]">trusted vendors</p><div className="mt-6 h-px bg-white/15"/><p className="mono mt-4 text-[11px] text-[#d3e8e8]">Stripe · AWS · Anthropic</p></div><div className="glass-dark specular rounded-[24px] p-6 sm:col-span-2"><p className="mono text-[10px] text-[#97c1c4]">VELOCITY / WINDOWED</p><div className="mt-8 flex flex-wrap items-end justify-between gap-5"><p className="display text-4xl">No surprises.</p><div className="flex items-end gap-1">{[28,44,36,58,48,74,54,92,68,80,61,72].map((h,i)=><i key={i} style={{height:h}} className="block w-2 rounded-t bg-[#a4d8d5]/60"/> )}</div></div><p className="mt-4 text-xs text-[#b8d4d6]">Rolling spend windows surface unusual velocity before it becomes exposure.</p></div></div></div></section>
    <section id="audit" className="relative z-10 mx-auto max-w-[1220px] px-6 py-24 md:px-10 md:py-36"><div className="grid items-center gap-16 md:grid-cols-[1fr_.9fr]"><div><p className="mono text-[10px] uppercase tracking-[.18em] text-[#4a7c84]">03 / Trust surface</p><h2 className="display mt-5 text-5xl font-light leading-[.94] text-[#173f48] md:text-7xl">The audit trail<br/><span className="font-extrabold">is the product.</span></h2><p className="mt-7 max-w-[420px] text-sm leading-7 text-[#55767c]">One immutable ledger for every intent, policy version, verdict, and human decision. Export it for finance. Query it for engineering. Trust it in a boardroom.</p><div className="mt-10 grid max-w-[450px] grid-cols-2 gap-x-8 gap-y-6 border-t border-[#aac9cc] pt-6"><div><p className="mono text-2xl text-[#173f48]">7,284</p><p className="mt-1 text-[10px] uppercase tracking-[.12em] text-[#628188]">decisions logged</p></div><div><p className="mono text-2xl text-[#173f48]">100%</p><p className="mt-1 text-[10px] uppercase tracking-[.12em] text-[#628188]">reason attached</p></div></div></div><div className="glass specular rounded-[28px] p-7"><div className="flex items-center justify-between border-b border-[#a9c7ca] pb-4"><span className="mono text-[10px] text-[#4d7b82]">AUDIT EVENT</span><span className="mono text-[10px] text-[#76979c]">#0007284</span></div><div className="space-y-5 py-6 text-sm"><div><p className="text-[11px] text-[#75959a]">EVENT</p><p className="mt-1 font-medium">Payment verdict: ESCALATE</p></div><div><p className="text-[11px] text-[#75959a]">REASON</p><p className="mt-1">Vendor outside approved allowlist</p></div><div><p className="text-[11px] text-[#75959a]">POLICY SNAPSHOT</p><p className="mono mt-1 text-[11px]">ARC-042 · v3.8 · sha 8d1…c24</p></div></div><div className="rounded-xl bg-[#c8e1e3]/60 p-4 text-[11px] text-[#466b73]"><span className="font-semibold text-[#173f48]">Awaiting human approval</span><br/>Maya Chen has 14 minutes remaining</div></div></div></section>
    <section id="contact" className="relative z-10 mx-6 mb-10 overflow-hidden rounded-[32px] bg-[#c2e1e3] px-6 py-20 text-center md:mx-auto md:max-w-[1220px] md:px-10"><div className="absolute -right-16 -top-28 h-72 w-72 rounded-full bg-[#efffff]/70 blur-3xl"/><p className="mono relative text-[10px] uppercase tracking-[.18em] text-[#4a7c84]">Ready when your agent is.</p><h2 className="display relative mx-auto mt-5 max-w-[700px] text-5xl font-light leading-[.92] text-[#173f48] md:text-7xl">Put a policy<br/><span className="font-extrabold">between intent and impact.</span></h2><a href="mailto:hello@thearcanum.in" className="ng-button relative mt-9 inline-flex items-center gap-3 rounded-full bg-[#087f83] px-6 py-4 text-sm font-semibold text-[#effafa]">Talk to Arcanum <Arrow/></a></section>
    <footer className="relative z-10 mx-auto flex max-w-[1220px] flex-col justify-between gap-8 px-6 pb-10 pt-4 md:flex-row md:items-end md:px-10"><div><p className="display text-[19px] font-extrabold tracking-[-.07em] text-[#173f48]">ARCANUM<span className="ml-1 align-top text-[8px] font-semibold tracking-[.15em] text-[#39848a]">/ ARC</span></p><p className="mt-3 text-xs text-[#69888d]">Governance for the autonomous economy.</p></div><div className="flex gap-6 text-xs text-[#55767c]"><a className="ng-link" href="#policy">Documentation</a><a className="ng-link" href="mailto:hello@thearcanum.in">Contact</a><span className="mono text-[10px]">© 2025</span></div></footer>
  </main>;
}