import { useEffect, useState, type ReactNode } from "react";

const rows = [
  { time: "09:41:08", agent: "procurement-bot", vendor: "AWS", amount: "$184.20", wallet: "0x3f…9a2c", verdict: "ALLOWED" },
  { time: "09:41:12", agent: "support-agent", vendor: "OpenAI", amount: "$740.00", wallet: "0x71…4be1", verdict: "BLOCKED" },
  { time: "09:41:16", agent: "growth-bot", vendor: "Anthropic", amount: "$2,100.00", wallet: "0xa8…c912", verdict: "ESCALATED" },
  { time: "09:41:19", agent: "procurement-bot", vendor: "AWS", amount: "$316.40", wallet: "0x3f…9a2c", verdict: "ALLOWED" },
];

function Arrow() { return <span aria-hidden="true" className="ml-2 inline-block transition-transform duration-300 group-hover:translate-x-1">↗</span>; }
function Reveal({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`ox-reveal ${className}`}>{children}</div>; }
function Rule({ children }: { children: ReactNode }) { return <div className="flex items-center gap-4 text-[10px] font-mono uppercase tracking-[.2em] text-[#8c6e5e]"><span className="h-px flex-1 bg-[#b89b73]/50" />{children}<span className="h-px flex-1 bg-[#b89b73]/50" /></div>; }

function Verdict({ value }: { value: string }) {
  const c = value === "BLOCKED" ? "bg-[#481214] text-[#f4e9d6]" : value === "ESCALATED" ? "border border-[#a5804c] text-[#815b2d]" : "bg-[#d6bc7b] text-[#3f241d]";
  return <span className={`inline-flex px-2.5 py-1 text-[9px] font-mono tracking-[.12em] ${c}`}>{value}</span>;
}

function Ledger() {
  const [visible, setVisible] = useState(1);
  useEffect(() => { const id = window.setInterval(() => setVisible(v => v >= rows.length ? 1 : v + 1), 2300); return () => window.clearInterval(id); }, []);
  return <div className="overflow-hidden border border-[#b89b73]/70 bg-[#f7edda] shadow-[12px_18px_0_rgba(92,26,27,.08)]">
    <div className="flex items-center justify-between border-b border-[#cdb693] px-5 py-4"><div className="flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-[#9a7137] shadow-[0_0_0_3px_#dfc99e]" /><span className="font-mono text-[10px] uppercase tracking-[.17em] text-[#72554a]">Live governed ledger</span></div><span className="font-mono text-[10px] text-[#9b7b68]">ARC / USDC</span></div>
    <div className="grid grid-cols-[1.25fr_1fr_.8fr_1fr_auto] gap-3 border-b border-[#d9c4a1] px-5 py-3 font-mono text-[9px] uppercase tracking-[.12em] text-[#997a67]"><span>Agent</span><span>Vendor</span><span>Amount</span><span>Wallet</span><span>Verdict</span></div>
    <div className="divide-y divide-[#e3ceb0]">{rows.map((r, i) => <div key={r.time} className={`grid grid-cols-[1.25fr_1fr_.8fr_1fr_auto] items-center gap-3 px-5 py-4 transition-all duration-700 ${i < visible ? "translate-y-0 opacity-100" : "translate-y-2 opacity-25"}`}><div><div className="text-[12px] font-semibold text-[#42251e]">{r.agent}</div><div className="mt-1 font-mono text-[9px] text-[#a38470]">{r.time} UTC</div></div><span className="text-[12px] text-[#76574a]">{r.vendor}</span><span className="font-mono text-[12px] tabular-nums text-[#42251e]">{r.amount}</span><span className="font-mono text-[10px] text-[#94725e]">{r.wallet}</span><Verdict value={r.verdict} /></div>)}</div>
    <div className="flex items-center justify-between border-t border-[#cdb693] px-5 py-3"><span className="font-mono text-[9px] text-[#9a7b68]">policy/v4.18 · 42ms median</span><span className="font-mono text-[9px] text-[#815b2d]">● streaming</span></div>
  </div>;
}

export function OxbloodBone() {
  return <main className="min-h-[100dvh] overflow-hidden bg-[#f1e5d0] text-[#42251e]" style={{ fontFamily: "'DM Sans', sans-serif" }}>
    <style>{`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Libre+Baskerville:wght@400;700&family=DM+Mono:wght@400;500&display=swap');
      .ox-display{font-family:'Libre Baskerville',serif}.ox-reveal{animation:ox-in .8s ease-out both}.ox-reveal:nth-child(2){animation-delay:.12s}.ox-reveal:nth-child(3){animation-delay:.22s}@keyframes ox-in{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}.ox-grain:before{content:'';position:fixed;inset:0;pointer-events:none;opacity:.05;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.85' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.45'/%3E%3C/svg%3E")}`}</style>
    <div className="ox-grain">
      <nav className="mx-auto flex max-w-[1180px] items-center justify-between px-6 py-7"><a href="#" className="ox-display text-[19px] font-bold tracking-[.12em] text-[#5c1a1b]">ARCANUM<span className="ml-2 text-[9px] align-top font-sans tracking-normal text-[#9a7137]">◈</span></a><div className="hidden items-center gap-9 text-[11px] font-medium uppercase tracking-[.16em] text-[#72554a] md:flex"><a className="transition-colors hover:text-[#5c1a1b]" href="#governed">The ledger</a><a className="transition-colors hover:text-[#5c1a1b]" href="#policies">Policies</a><a className="transition-colors hover:text-[#5c1a1b]" href="#proof">Assurance</a></div><a href="#contact" className="group border border-[#5c1a1b] px-4 py-2 text-[10px] font-bold uppercase tracking-[.14em] text-[#5c1a1b] transition hover:bg-[#5c1a1b] hover:text-[#f1e5d0]">Request a briefing<Arrow /></a></nav>
      <section className="mx-auto grid max-w-[1180px] gap-14 px-6 pb-28 pt-16 md:grid-cols-[.9fr_1.1fr] md:items-end md:pt-28"><Reveal><p className="mb-7 font-mono text-[10px] uppercase tracking-[.23em] text-[#8a633c]">A custody standard for autonomous capital</p><h1 className="ox-display max-w-[680px] text-[clamp(46px,6.5vw,88px)] leading-[1.04] tracking-[-.05em] text-[#5c1a1b]">Every dollar<br /><i className="text-[#946b3e]">answers</i> to someone.</h1><p className="mt-8 max-w-[460px] text-[17px] leading-7 text-[#684a40]">ARCanum governs AI-agent USDC wallets on Arc. Set the rule once. We check every spend, block the exceptions, and bring a human in when judgment matters.</p><a href="#governed" className="group mt-9 inline-flex items-center bg-[#5c1a1b] px-6 py-4 text-[11px] font-bold uppercase tracking-[.14em] text-[#f4e9d6] transition hover:bg-[#431517] hover:shadow-[5px_5px_0_#b89b73]">See a dollar governed<Arrow /></a></Reveal><Reveal className="md:pb-4"><div className="border-l border-[#a5804c] pl-7"><div className="mb-7 flex justify-between font-mono text-[10px] uppercase tracking-[.14em] text-[#8c6e5e]"><span>Charter 001 / operating view</span><span>● live</span></div><div className="grid grid-cols-2 gap-y-8 border-t border-[#b89b73]/60 pt-6"><div><strong className="ox-display text-4xl font-normal text-[#5c1a1b]">$2.4M</strong><p className="mt-2 text-[10px] uppercase tracking-[.14em] text-[#8c6e5e]">governed this month</p></div><div><strong className="ox-display text-4xl font-normal text-[#5c1a1b]">42<span className="text-xl">ms</span></strong><p className="mt-2 text-[10px] uppercase tracking-[.14em] text-[#8c6e5e]">median policy check</p></div></div></div></Reveal></section>
      <section id="governed" className="bg-[#5c1a1b] px-6 py-24 text-[#f1e5d0]"><div className="mx-auto max-w-[1180px]"><Rule>How a dollar gets governed</Rule><div className="mt-16 grid gap-12 md:grid-cols-[.75fr_1.25fr] md:items-start"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[#d6bc7b]">No blind spots</p><h2 className="ox-display mt-5 text-4xl leading-tight">The ledger<br />does the arguing.</h2><p className="mt-6 max-w-sm text-[14px] leading-6 text-[#dbc9b5]">A transaction earns its way through three gates before it touches the chain.</p></div><div className="space-y-0">{[["01","Policy check","Per-tx and daily caps, vendor allowlists, wallet identity.","$500 / tx · $5,000 / day"],["02","Allow or block","An out-of-policy request stops before settlement.","OpenAI · $740.00 · BLOCKED"],["03","Escalate to a human","Ambiguous spend becomes a decision, not a loophole.","Anthropic · $2,100.00 · REVIEW"]].map(([n,t,d,m])=><div key={n} className="grid grid-cols-[50px_1fr_auto] gap-5 border-b border-[#9e6964]/50 py-7"><span className="font-mono text-[11px] text-[#d6bc7b]">{n}</span><div><h3 className="ox-display text-xl">{t}</h3><p className="mt-2 text-[13px] leading-5 text-[#dbc9b5]">{d}</p></div><span className="self-center text-right font-mono text-[10px] text-[#d6bc7b]">{m}</span></div>)}</div></div></div></section>
      <section className="mx-auto max-w-[1180px] px-6 py-28"><div className="mb-12 grid gap-5 md:grid-cols-[.65fr_1.35fr]"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[#8a633c]">The quiet proof</p><h2 className="ox-display mt-4 text-4xl leading-tight text-[#5c1a1b]">Watch the<br />rules hold.</h2></div><p className="max-w-md self-end text-[15px] leading-6 text-[#76574a]">No dashboards to babysit. No weekly reconciliation. A live record of what your agents asked to buy—and why the answer was yes, no, or not yet.</p></div><Ledger /></section>
      <section id="policies" className="border-y border-[#b89b73]/60 bg-[#e9d8ba] px-6 py-24"><div className="mx-auto max-w-[1180px]"><Rule>Policy, made explicit</Rule><div className="mt-16 grid gap-14 md:grid-cols-[1fr_1fr]"><div><h2 className="ox-display max-w-md text-4xl leading-tight text-[#5c1a1b]">A charter for every agent.</h2><p className="mt-6 max-w-md text-[15px] leading-6 text-[#76574a]">Give procurement-bot a ceiling, a list of vendors, and a path to approval. Arcanum enforces the rest at the moment of spend.</p><a href="#contact" className="group mt-8 inline-flex items-center text-[11px] font-bold uppercase tracking-[.15em] text-[#5c1a1b]">Explore policy controls<Arrow /></a></div><div className="border border-[#b89b73] bg-[#f5e8d1] p-7 shadow-[10px_10px_0_rgba(92,26,27,.08)]"><div className="flex justify-between border-b border-[#cfb998] pb-5"><span className="font-mono text-[11px] text-[#5c1a1b]">procurement-bot</span><span className="font-mono text-[10px] text-[#8a633c]">POLICY / V4.18</span></div><div className="space-y-5 pt-6 font-mono text-[11px] text-[#684a40]"><p><span className="text-[#9a7137]">ALLOW</span><span className="ml-5">vendors = AWS, Anthropic</span></p><p><span className="text-[#9a7137]">LIMIT</span><span className="ml-5">$500 / transaction</span></p><p><span className="text-[#9a7137]">LIMIT</span><span className="ml-5">$5,000 / rolling day</span></p><p><span className="text-[#9a7137]">ESCALATE</span><span className="ml-5">amount &gt; $500</span></p></div></div></div></div></section>
      <section id="proof" className="mx-auto max-w-[1180px] px-6 py-28"><div className="grid gap-14 md:grid-cols-[1.2fr_.8fr]"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[#8a633c]">Assurance / in plain view</p><blockquote className="ox-display mt-6 max-w-2xl text-[clamp(28px,4vw,52px)] leading-[1.17] text-[#5c1a1b]">“Autonomy is only useful when finance can prove where it stopped.”</blockquote><p className="mt-8 font-mono text-[10px] uppercase tracking-[.16em] text-[#8c6e5e]">— Mira Voss, Controller, Nera Systems</p></div><div className="border-l border-[#b89b73] pl-8"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[#8a633c]">The record</p><div className="mt-7 space-y-5 text-[13px] text-[#76574a]"><p className="flex justify-between border-b border-[#d0b996] pb-4"><span>Non-custodial</span><b className="font-mono font-normal text-[#5c1a1b]">your keys</b></p><p className="flex justify-between border-b border-[#d0b996] pb-4"><span>Settlement</span><b className="font-mono font-normal text-[#5c1a1b]">Arc / USDC</b></p><p className="flex justify-between border-b border-[#d0b996] pb-4"><span>Audit history</span><b className="font-mono font-normal text-[#5c1a1b]">immutable</b></p></div></div></div></section>
      <section id="contact" className="bg-[#5c1a1b] px-6 py-24 text-center text-[#f1e5d0]"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[#d6bc7b]">Put a charter behind your agents</p><h2 className="ox-display mx-auto mt-5 max-w-2xl text-5xl leading-tight">Make every spend<br /><i className="text-[#d6bc7b]">accountable.</i></h2><a href="mailto:briefing@thearcanum.in" className="group mt-9 inline-flex bg-[#d6bc7b] px-7 py-4 text-[11px] font-bold uppercase tracking-[.14em] text-[#4a211d] transition hover:bg-[#f1e5d0] hover:shadow-[5px_5px_0_#301012]">Request a private briefing<Arrow /></a></section>
      <footer className="mx-auto flex max-w-[1180px] flex-col gap-5 px-6 py-8 text-[10px] uppercase tracking-[.14em] text-[#8c6e5e] md:flex-row md:items-center md:justify-between"><span className="ox-display text-[15px] font-bold tracking-[.12em] text-[#5c1a1b]">ARCANUM</span><span>Non-custodial governance for AI capital</span><span>thearcanum.in · © 2024</span></footer>
    </div>
  </main>;
}