/* Warm Ledger runtime tokens: light (warm paper) by default, dark (foundry
   black-grid) under `html.wl-dark`. Values live in apps' globals.css. */
export const foundryColors = {
  ink: "var(--wl-ink-fill)",
  obsidian: "var(--wl-obsidian)",
  "coal-grid": "var(--wl-page)",
  "panel-dark": "var(--wl-panel-dark)",
  "panel-mid": "var(--wl-panel-mid)",
  "panel-top": "var(--wl-panel2)",
  "panel-raised": "var(--wl-panel)",
  "panel-hover": "var(--wl-panel-hover)",
  "panel-rail": "var(--wl-panel-rail)",
  "panel-muted": "var(--wl-panel-muted)",
  "line-subtle": "var(--wl-hairline)",
  "line-muted": "var(--wl-line-muted)",
  "line-strong": "var(--wl-line-strong)",
  "line-active": "var(--wl-line-active)",
  "ash-muted": "var(--wl-text-muted)",
  "ash-soft": "var(--wl-text-secondary)",
  ash: "var(--wl-text-body)",
  "ash-bright": "var(--wl-text-primary)",
  hazard: "var(--wl-signal)",
  "hazard-dark": "var(--wl-hazard-tint)",
  rust: "var(--wl-red)",
  amber: "var(--wl-amber)",
  "steel-green": "var(--wl-green)",
  "steel-cyan": "var(--wl-cat-compute)",
  "cat-api": "var(--wl-cat-api)",
  "cat-compute": "var(--wl-cat-compute)",
  "cat-data": "var(--wl-cat-data)",
  "cat-subcontract": "var(--wl-cat-sub)",
  "cat-other": "var(--wl-cat-other)",
} as const;

const foundryTailwindPreset = {
  darkMode: "class",
  theme: {
    extend: {
      colors: foundryColors,
      fontFamily: {
        mono: ["var(--font-mono)", "DM Mono", "monospace"],
        cond: ["var(--font-cond)", "Inter Tight", "sans-serif"],
        body: ["var(--font-body)", "Inter Tight", "sans-serif"],
      },
      fontSize: {
        "fdy-8": ["8px", "1.2"],
        "fdy-9": ["9px", "1.3"],
        "fdy-10": ["10px", "1.4"],
        "fdy-11": ["11px", "1.4"],
        "fdy-12": ["12px", "1.45"],
        "fdy-13": ["13px", "1.45"],
        "fdy-14": ["14px", "1.5"],
        "fdy-15": ["15px", "1.5"],
        "fdy-16": ["16px", "1.5"],
        "fdy-17": ["17px", "1.4"],
        "fdy-18": ["18px", "1.35"],
        "fdy-24": ["24px", "1.2"],
        "fdy-26": ["26px", "1.15"],
        "fdy-30": ["30px", "1.1"],
        "fdy-34": ["34px", "1.05"],
        "fdy-36": ["36px", "1.05"],
        "fdy-40": ["40px", "1"],
        "fdy-52": ["52px", "0.95"],
        "fdy-64": ["64px", "0.9"],
        "fdy-72": ["72px", "0.8"],
        "fdy-96": ["96px", "0.78"],
        "fdy-112": ["112px", "0.74"],
      },
      spacing: {
        chrome: "52px",
        nav: "40px",
        "drawer-lg": "432px",
        "docs-rail": "268px",
      },
      borderRadius: {
        none: "0",
      },
      boxShadow: {
        "fdy-drawer": "0 0 60px rgba(0,0,0,0.7)",
      },
    },
  },
} as const;

export default foundryTailwindPreset;
